apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appname}}
  namespace: teamdatajegerne
  labels:
    team: teamdatajegerne 
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - NAVident
        groups:
        {{#each azuregroupid as |groupid|}}
          - id: {{groupid}}
        {{/each}}
      replyURLs:
      {{#each replies as |url|}}
         - {{url}}
      {{/each}}
  tokenx:
    enabled: true
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  liveness:
    path: internal/isAlive
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: internal/isReady
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/metrics

  gcp:
    sqlInstances:
      - name: behandlingskatalog
        type: POSTGRES_16
        tier: db-custom-1-3840
        databases:
          - name: behandlingskatalogdb
            envVarPrefix: DB
        flags:
          - name: max_connections
            value: "50"
  accessPolicy:
    inbound:
      rules:
        - application: behandlingskatalog-frontend
        - application: etterlevelse-backend
        - application: pdl-pip-sync
          namespace: pdl
          cluster: prod-fss
        - application: pdl-behandlingskatalog-proxy
          namespace: pdl
          cluster: prod-gcp
        - application: nada-backend
          namespace: nada
    outbound:
      rules:
        - application: nom-api
          namespace: nom
          cluster: {{cluster_location}}
      external:
        - host: {{teamcat_ingress}}
        - host: {{termcat_ingress}}
        - host: kodeverk-api.nav.no
        - host: slack.com
  envFrom:
    - configmap: behandlingskatalogcfg
    - secret: polly-enckey
    - secret: polly-mail-pwd
  env:
  {{#each env}}
   - name: {{this.name } }
     value: {{this.value}}
  {{/each}}

  filesFrom:
    - secret: polly-aareg-integration-key
