apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{appname}}
  namespace: teamdatajegerne
  labels:
    team: teamdatajegerne 
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - NAVident
        groups:
        {{#each group id as |asuregroupid|}}
          - {{asuregroupid}}
        {{/each}}
      replyURLs:
      {{#each replies as |url|}}
         - {{url}}
      {{/each}}
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  liveness:
    path: internal/isAlive
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: internal/isReady
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /internal/metrics

  gcp:
    sqlInstances:
      - name:
        type: POSTGRES_12
        databases:
          - name:
            envVarPrefix:
  accessPolicy:
    inbound:
      rules:
        - application: behandlingskatalog-frontend
        - application: etterlevelse-backend
    outbound:
      external:
        - host: {{teamcat_ingress}}
        - host: slack.com

  webproxy: true
  envFrom:
    - configmap: pollycfg
    - secret: polly-enckey
    - secret: polly-mail-pwd
  filesFrom:
    - secret: polly-aareg-integration-key
