apiVersion: v1
data:
  AZURE_APP_MAIL_USER: srvPollyMail@nav.no
  AZURE_CLIENT_GROUPS: 7d275d5e-59a5-473d-b530-a9091b3de4c6
  AZURE_CLIENT_GROUPS_ADMIN: bf05a29f-6f80-4da1-b419-22c802fd41e7
  AZURE_CLIENT_GROUPS_SUPER: b0d4bdd3-40fc-4feb-8147-a18388d3edfa
  BIGQUERY_AUTH_PROJECTID: teamdatajegerne-prod-c8b1
  BIGQUERY_AAREG_DATASETNAME: aareg_avtaler
  BIGQUERY_AAREG_PROJECTID: teamcrm-prod-31a7
  BIGQUERY_AAREG_TABLENAME: aareg_avtaler_for_tilgang
  CLIENT_COMMON_CODE_NAV_URL: https://kodeverk-api.nav.no/api
  CLIENT_TEAMCAT_URL: https://teamkatalog-api.intern.nav.no
  CLIENT_TERM_CATALOG_URL: https://begrepskatalog-api.intern.nav.no/api/dcat
  ENVIRONMENT_CLASS: prod
  GOOGLE_APPLICATION_CREDENTIALS: /var/run/secrets/polly_aareg_integration_key.json
  POLLY_SECURITY_REDIRECT_URIS: https://behandlingskatalog.intern.nav.no, https://behandlingskatalog.ansatt.nav.no
kind: ConfigMap
metadata:
  name: behandlingskatalogcfg
  namespace: teamdatajegerne
