version: 2
updates:
- package-ecosystem: docker
  directory: "/apps/backend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/apps/frontend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/apps/frontend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/apps/backend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
