sudo: required
services:
- docker
language: java
jdk:
- openjdk11
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
  - TZ='Europe/Oslo'
  - RELEASE_VERSION="$(git fetch --unshallow || true && git rev-list --count $TRAVIS_COMMIT)"
  - APPLICATION_NAME='data-catalog-backend'
  - DOCKER_IMAGE_FULL_NAME="navikt/$APPLICATION_NAME:$RELEASE_VERSION"
  - DOCKER_USERNAME=naviktdocker
  - secure: e0j7pHDiqwQNlP/INJQW95KHQq9T6Q0hk9mqvoRfx2tCC+mI2MK0GmCzB7tM95rShh/7UXNJz1NuS5ixFSb9pB6r09xNIGltLUs9pvYbyDEFcTDmfwkTNBPBSSwVaPFXO2rjFnEgXwvbaMNIXTCX7QsbXUh7bFqehIoZpoCBobLL+tI8APQo0zF7MdvqdGfr7Gqyk3+Hk9X5zBYDDlfOGOHxET3A85vEkRwgSYtdmSkHJgo2oxxJgIs/GuGL3Fw3DoGskDhz5g7zgsHfCq5/Ecxql3XHf/URyYC0kKRJC+xLdUJsJ3EqErJjBxk406ion2d3lRg70ibdKgt3WroLJMzfj7jPN5mM6WpJxUP2kPcmj9hn0PN8/2/iABVyc9s0Dg21XGdHWU300qjXWbNcD+uSlMGOOfa0dlj669tryrJ6tOo9mVG3ntAxGfCJ+21qZdrn2DoUb6C2Ntq7fUbo1u6eQqVirwWfJzvHf41SWFxtoS2JKOVT476YaW/62F/ZehC/oOgOz5UD1b7p9zAxJwqWrPJ6z4AHlJZWzCwgs6JbJl1xy+ipN+mZPJMxh3yXQcAKfcEdqrB5/KXrhxvg0WXmzrsdNhR9ZqVrK5+zNE4G7MHPSQG/T5VSxX0w+KtRm7WUX+CtpU4VM+ECfZLepz/PqWPlBktIMosweDUO84Y=
before_install:
- openssl aes-256-cbc -K $encrypted_bd8eff391c8f_key -iv $encrypted_bd8eff391c8f_iv
  -in travis/datajegerne-private-key.enc -out travis/datajegerne-private-key.pem -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export INSTALLATION_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/datajegerne-private-key.pem
  $GITHUB_APP_ID`)
script:
- mvn install
- git config user.name datajegerne[bot]
- git config user.email datajegerne[bot]@users.noreply.github.com
- docker build --build-arg app_name="$APPLICATION_NAME" -t "$DOCKER_IMAGE_FULL_NAME"
  .
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x travis/deploy.sh && travis/deploy.sh
  on:
    branch: master
after_deploy:
- git remote add auth-origin "https://x-access-token:${INSTALLATION_TOKEN}@github.com/${TRAVIS_REPO_SLUG}"
- git tag $RELEASE_VERSION
- git push auth-origin --tags
