apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: polly
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  ingresses:
    - "https://polly.nais.preprod.local"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: internal/isAlive
    initialDelay: 30
  readiness:
    path: internal/isReady
    initialDelay: 30
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
    requests:
      memory: 528Mi
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: internal/metrics
  leaderElection: true
  webproxy: true
