apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: data-catalog-backend
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  ingresses:
    - "https://datakatalog.prod-sbs.nais.io/backend"
    - "https://datakatalog.nav.no/backend"
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  liveness:
    path: backend/internal/isAlive
    initialDelay: 60
  readiness:
    path: backend/internal/isReady
    initialDelay: 60
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
    requests:
      memory: 528Mi
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: backend/internal/metrics
