import {IStrings} from './intl'

export const no: IStrings = {
  //aareg avtaler
  aaregContracts: 'Utleveringsavtaler i Aa-registeret',
  organisationNumber: 'Organisasjonsnummer',
  aaregContractNumber: 'Avtalenummer',
  showAaregTable: 'Vis Aa-reg avtaler',
  hideAaregTable: 'Skjul Aa-reg avtaler',
  createdDate: 'Dato opprettet',
  accessType: 'Type tilgang',
  API: 'API',
  extract: 'Uttrekk',
  webLookup: 'Web-oppslag',
  incidents: 'Hendelser',
  consumer: 'Konsument',
  contractAareg: 'Avtale',
  purposeForProcess: 'Formål med behandlingen',
  authorityAndGroundsForDelivery: 'NAVs hjemmel for utlevering',
  consumerAuthorityForProcess: 'Konsumentens hjemmel for behandlingen',
  purposeAuthorityLegalBasis: 'Formål, Hjemmel og Behandlingsgrunnlag',
  available: 'Tilgjengelig',
  unavailable: 'Ikke tilgjengelig',

  informationType: 'Opplysningstype',
  informationTypes: 'Opplysningstyper',
  informationTypeSearch: 'Søk opplysningstyper',
  search: 'Søk',
  term: 'Begrepsdefinisjon',
  termEditHeader: 'Begrepsdefinisjon (oppslag i Begrepskatalogen)',
  purpose: 'Formål',
  processPurpose: 'Behandlingsformål',
  processNumber: 'Behandlingsnummer',
  purposeOfTheProcess: 'Formål med behandlingen',
  purposeDescription: 'Overordnet formålsbeskrivelse',
  sensitivity: 'Type personopplysning',
  processingActivities: 'Behandlingsaktiviteter',
  process: 'Behandling',
  dpProcess: 'Nav som databehandler',
  dpProcesses: 'Databehandlinger',
  processes: 'Behandlinger',
  legalBasis: 'Behandlingsgrunnlag for hele behandlingen',
  legalBasisShort: 'Behandlingsgrunnlag',
  legalBasesShort: 'Behandlingsgrunnlag',
  subjectCategories: 'Personkategori',
  summarySubjectCategories: 'Personkategorier oppsummert',
  processContainsSubjectCategory: "Behandlingen inneholder allerede personkategorien '{0}' for opplysningstype '{1}'",
  nationalLaw: 'Nasjonal lov',
  gdprArticle: 'GDPR artikkel',
  orgMaster: 'Master i NAV',
  orgMasterInfTypeHeader: 'Opplysningstyper systemet er master for',
  productTeam: 'Team',
  productTeamFromTK: 'Team (Oppslag i Teamkatalogen)',
  productTeamFromTKHelpText: 'Angi hvilke team som har forvaltningsansvaret for IT-systemene.',
  product: 'Produkt',
  products: 'Produkter',
  team: 'Team',
  productArea: 'Område',
  system: 'System',
  systems: 'Systemer',
  disclosure: 'Utlevering',
  disclosures: 'Utleveringer',
  dispatcher: 'Avsender',
  linkDisclosurePage: 'Lenke til side for utleveringer',
  editDisclosure: 'Rediger utlevering',
  documents: 'Dokumenter',
  dataAccessClass: 'Datatilgangsklasse',
  dataAccessClassSelect: 'Velg datatilgangsklasse',
  thirdParty: 'Ekstern part',
  thirdParties: 'Eksterne parter',
  alerts: 'Varsler',
  policy: 'Polis',
  usage: 'Bruk',
  and: 'og',
  with: 'med',
  pollyOrg: 'NAV',
  or: 'eller',
  remove: 'Fjern',
  yes: 'Ja',
  no: 'Nei',
  seeExternalLink: 'Se ekstern lenke',
  processActivity: 'Behandlingsaktivitet',
  aboutUs: 'Om Behandlingskatalogen',
  includeConservationPlan: 'Omfattes av NAVs bevarings- og kassasjonsvedtak?',
  unclarified: 'Uavklart',
  unknown: 'Uavklart',
  notFilled: 'Ikke utfylt',
  filled: 'Utfylt',
  automation: 'Automatisering og profilering',
  automaticProcessing: 'Helautomatisk behandling',
  isAutomationNeeded: 'Treffes det et vedtak eller en avgjørelse som er basert på helautomatisert behandling?',
  automaticProcessingExtra:
    'Treffes det et vedtak eller en avgjørelse som er basert på helautomatisert behandling av personopplysninger? Altså avgjørelser uten menneskelig innvirkning.',
  profiling: 'Profilering',
  isProfilingUsed: 'Benyttes profilering?',
  profilingExtra:
    'Med profilering mener vi at personopplysninger behandles automatisk for å kunne analysere eller forutsi noe om preferanser, evner eller behov til en enkeltperson. analysering av personopplysninger for å kunne forutsi noe om en enkeltperson, f.eks. personens preferanser, evner eller behov.',
  processor: 'Databehandler',
  processors: 'Databehandlere',
  dpProcessDataProcessor: 'Databehandleravtale med behandlingsansvarlig',
  subDataProcessor: 'Underdatabehandler',
  isProcessorUsed: 'Benyttes databehandler(e)?',
  isSubDataProcessorUsed: 'Benyttes underdatabehandler(e)?',
  processorYes: 'Databehandler benyttes',
  help: 'Hjelp',
  helpTooltip: 'På navets personvernsider finner du informasjon til hjelp for utfylling.',
  dpProcessProcessorYes: 'Databehandleravtale inngått',
  processorNo: 'Databehandler benyttes ikke',
  dpProcessDataProcessorNo: 'Databehandleravtale ikke inngått',
  processorUnclarified: 'Uavklart om databehandler brukes',
  dpProcessDataProcessorUnclarified: 'Uavklart om databehandleravtale',
  processorExtra: 'Brukes det databehandler for å utføre behandlingen/behandle personopplysninger',
  processorAgreement: 'Ref. til databehandleravtale',
  processorAgreementPlaceholder: '(f.eks. lenke til Websak, Confluence e.l.)',
  processorOutsideEU: 'Utenfor EU / EØS',
  isDataProcessedOutsideEUEEA: 'Behandler databehandler personopplysninger utenfor EU/EØS?',
  isSubDataProcessedOutsideEUEEA: 'Behandler underdatabehandler personopplysninger utenfor EU/EØS?',
  isDataProcessedOutsideEUEEAHelpText: 'En databehandler er en virksomhet som behandler personopplysninger på NAVs vegne.',
  transferGroundsOutsideEUEEA: 'Overføringsgrunnlag for behandling utenfor EU/EØS',
  transferGroundsOutsideEUEEAOther: 'Andre overføringsgrunnlag',
  countries: 'Land',
  includeDefaultDocument: 'Standard opplysningstyper',
  from: 'fra',
  retained: 'Lagres i',
  retention: 'Lagringsbehov',
  processWithIncompleteRetention: 'Behandlinger med ufullstendig lagringstid: ',
  retentionPlan: 'Er området omfattet av etatens bevarings- og kassasjonsvedtak?',
  retentionPlanYes: 'Omfattes av NAVs bevarings- og kassasjonsvedtak',
  retentionPlanNo: 'Omfattes ikke av NAVs bevarings- og kassasjonsvedtak',
  retentionPlanUnclarified: 'Uavklart om omfattes av NAVs bevarings- og kassasjonsvedtak',
  retentionMonths: 'Lagringsbehov for NAV',
  retentionStart: 'Lagringsbehovet beregnes fra følgende tidspunkt eller hendelse',
  retentionDescription: 'Begrunnelse',
  retentionDescriptionPlaceHolder: '(f.eks. lenke til Websak, Confluence e.l.)',
  retentionReference: 'Ref. til relevant dokumentasjon',
  retentionPieChartTitle: 'Omfattes av NAVs bevarings- og kassasjonsvedtak',
  years: 'år',
  months: 'måneder',
  lastEvents: 'Siste hendelser',
  userLastChanges: 'Mine siste endringer',
  exceptionalUsage: 'Brukes unntaksvis',
  overallPurpose: 'Overordnet formål',
  overallPurposeActivity: 'Overordnet behandlingsaktivitet',
  loggedInStatus: 'Du er logget inn og kan',
  notLoggedInStatus: 'Du er ikke logget inn men kan',
  couldntLoad: 'Kunne ikke laste inn siden',
  couldntLoadTerm: 'Kunne ikke finne begrepsdefinisjon',
  noTerm: 'Ingen begrepsdefinisjon angitt',
  couldntLoadTeam: 'Kunne ikke finne team',
  informationTypeCreate: 'Opprett opplysningstype',
  informationTypeExists: 'Informasjonstypen eksisterer allerede',
  documentExists: 'Dokument med samme navn eksisterer allerede',
  sensitivitySelect: 'Velg type personopplysning',
  nameWrite: 'Skriv inn navn',
  categoriesWrite: 'Skriv inn og legg til kategorier',
  sourcesWrite: 'Skriv inn og legg til kilder',
  keywordsWrite: 'Legg til nøkkelord',
  searchWordsWrite: 'Legg til søkeord',
  orgMasterSelect: 'Velg master',
  purposeSelect: 'Velg overordnet behandlingsaktivitet',
  purposeNotFound: 'Fant ingen formål',
  processingActivityUse: 'Brukes til behandlingsaktivitet',
  informationTypeExternalUse: 'Utleveres til',
  policyEdit: 'Rediger behandling for opplysningstype',
  policyNew: 'Opprett behandling for opplysningstype',
  policyAdd: 'Legg til opplysningstyper brukt i behandlingen',
  processEdit: 'Rediger behandling for opplysningstype',
  processingActivitiesNew: 'Opprett ny behandling',
  riskOwner: 'Risikoeier',
  riskOwnerFunction: 'Risikoeier funksjon',
  riskOwnerFunctionBinder: 'i funksjon',
  commonExternalProcessResponsible: 'Felles behandlingsansvarlig',
  commonExternalProcessResponsibleHelpText: 'Er NAV behandlingsansvarlig sammen med annen virksomhet?',
  processingActivitiesEdit: 'Rediger behandling',
  processNew: 'Legg til ny behandling',
  processCreated: 'Behandling opprettet',
  doYouWantToAddPolicies: 'Vil du legge til opplysningstyper?',
  addPolicies: 'Legg til opplysningstyper enkeltvis',
  addDefaultDocument: 'Legg til standardopplysningstyper',
  legalBasisNotFound: 'Fant ingen rettslige grunnlag',
  legalBasisNew: 'Behandlingsgrunnlag',
  legalBasisAdd: 'Legg til nytt behandlingsgrunnlag',
  article6HelpText: 'Alle behandlinger av personopplysninger krever et behandlingsgrunnlag iht. personopplysningsloven artikkel 6.',
  article9HelpText: 'Alle behandlinger av særlige kategorier (sensitive) av personopplysninger krever i tillegg et behandlingsgrunnlag iht personopplysningsloven artikkel 9.',
  addArticle6: 'Behandlingsgrunnlag',
  addArticle9: 'Behandlingsgrunnlag for særlige kategorier',
  cardHeaderArticle6: 'Behandlingsgrunnlag',
  cardHeaderArticle9: 'Behandlingsgrunnlag for særlige kategorier',
  placeHolderArticle6: 'Velg fra artikkel 6',
  placeHolderArticle9: 'Velg fra artikkel 9',
  numberOfProcessesWithUnknownLegalBasis: 'Rettslig grunnlag uavklart',
  numberOfProcessesWithoutArticle6LegalBasis: 'Artikkel 6 mangler',
  numberOfProcessesWithoutArticle9LegalBasis: 'Artikkel 9 mangler',
  processesWithUnknownLegalBasis: 'Behandlinger med rettslig grunnlag uavklart',
  processesWithoutArticle6LegalBasis: 'Behandlinger med rettslig grunnlag artikkel 6 mangler',
  processesWithoutArticle9LegalBasis: 'Behandlinger med rettslig grunnlag artikkel 9 mangler',
  withoutArticle6LegalBasisHelpText: 'Alle behandlinger av personopplysninger må ha et rettslig grunnlag iht. personopplysningsloven artikkel 6.',
  withoutArticle9LegalBasisHelpText:
    'Behandling av personopplysninger som anses som særlige kategorier (tidl. sensitive opplysninger) krever et ytterligere behandlingsgrunnlag iht. personopplysningsloven art. 9',
  unknownLegalBasisHelpText: 'Alle behandlinger av personopplysninger må ha et rettslig grunnlag iht. personopplysningsloven artikkel 6.',
  incompleteLegalBasis: 'Ufullstendig behandlingsgrunnlag',
  gdprSelect: 'Velg GDPR artikkel',
  nationalLawSelect: 'Velg lov eller forskrift',
  descriptionWrite: 'Skriv inn beskrivelse',
  descriptionWriteLegalBasesF: 'Spesifiser interessen',
  descriptionWriteLegalBasesCE: 'Legg inn paragraf (§) eller kapittel',
  definitionWrite: 'Søk definisjoner',
  subjectCategoriesNotFound: 'Fant ingen kategorier av personer',
  legalBasesProcess: 'Bruker behandlingens rettslige grunnlag',
  legalBasesUndecided: 'Uavklart',
  legalBasesOwn: 'Har eget Behandlingsgrunnlag',
  notAllowedMessage: 'Du har ikke tilgang til denne siden.',
  confirmDeleteHeader: 'Bekreft sletting',
  confirmDeletePolicyText: 'Bekreft sletting av behandling for opplysningstypen',
  deleteProcessText: 'Er du sikker på at du vil slette behandlingen? Dersom behandlingen er opphørt skal den i stedet markeres med å sette til og med dato på behandlingen.',
  deleteProcessorText: 'Er du sikker på at du vil slette databehadler?',
  confirmDeleteProcessText: 'Bekreft sletting av behandlingen ',
  confirmDeleteProcessorText: 'Bekreft sletting av databehandler ',
  confirmDeleteDocumentText: 'Bekreft sletting av dokument ',
  confirmDeleteDpProcess: 'Bekreft sletting av databehandlingen',
  cannotDeleteProcess: 'Kan ikke slette behandlingen {0}, den inneholder fortsatt {1} opplysningstyp(er)',
  confirmDeleteInformationTypeText: 'Bekreft sletting av opplysningstypen ',
  cannotDeleteInformationTypes: 'Kan ikke slette opplysningstypen {0} da den er',
  informationTypeHasPolicies: ' knyttet til {0} behandling(er)',
  informationTypeHasDocuments: ' knyttet til {0} dokument(er)',
  startIllustration: 'Illustrasjon av en prosess',
  treasureIllustration: 'Illustration av en skatt',
  legalbasisGDPRArt9Info: 'Opplysningstyper som er særlige kategorier krever art. 9',
  legalBasisInfo: 'For artikkel 6(c, e og f) trengs det videre spesifisering.',
  disclosureSelect: 'Velg ekstern part',
  createThirdPartyModalTitle: 'Opprett utlevering til ekstern part',
  disclosuresToThirdParty: 'Utleveringer til ekstern part',
  retrievedFromThirdParty: 'Innhentinger fra ekstern part',
  usageNotFound: 'Fant ingen bruk',
  newValue: 'Ny verdi',
  replace: 'Erstatt',
  replaceAllUse: 'Erstatt all bruk',
  recipientPurpose: 'Mottakers formål',
  legalBasisComplete: 'Lukk behandlingsgrunnlag redigering før lagring',
  validityOfProcess: 'Gyldighetsperiode for behandlingen',
  validityOfPolicy: 'Gyldighetsperiode for bruk av opplysningstypen i denne behandlingen',
  chooseDocument: 'Velg et dokument for å starte',
  addDocument: 'Legg til opplysningstyper fra dokument',
  searchDocuments: 'Søk dokumenter',
  addOneInformationType: 'Legg til én opplysningstype',
  addCollectionOfInformationTypes: 'Legg til en samling av opplysningstyper',
  groupByProcessingActivities: 'Grupper etter behandlingsaktivitet',
  showAll: 'Vis alle',
  emptyTable: 'Ingen',
  emptyMessage: 'Ikke angitt',
  pageNotFound: 'Oida 404! Fant ikke den siden der nei',
  createDocument: 'Opprett dokument',
  searchDocumentPlaceholder: 'Søk dokumenter',
  eventType: 'Hendelsetype',
  disclosurePurpose: 'Formål med utlevering',
  departmentSelect: 'Velg avdeling',
  subDepartmentSelect: 'Velg linje',
  teamSelect: 'Velg team',
  informationtypesUsedInDocument: 'Opplysningstyper i dokumentet',
  editDocument: 'Rediger dokument',
  completeness: 'Kompletthet',
  overview: 'Oversikt',
  searchProcess: 'Søk etter behandlinger',
  relatedProcesses: 'Relaterte behandlinger',
  frontPageStartMessage: 'Velg en sti!',

  dpProcessTitle: 'Databehandlingen',
  dpProcessPageTitle: 'Behandlinger hvor NAV er databehandler',
  thirdPartyDpProcessTableTitle: 'NAV er databehandler for {0} i følgende behandlinger',
  article9: 'Behandles det særlige kategorier av personopplysninger?',
  article10: 'Behandles det personopplysninger om straffedommer og lovovertredelser?',
  createDpProcess: 'Opprett ny behandling',
  dpProcessDuplicatedError: 'Databehandlingen eksisterer allerede.',
  externalProcessResponsible: 'Behandlingsansvarlig',

  nameDpProcessHelpText: 'Et kort navn som beskriver hva behandlingen går ut på, f.eks. saksbehandling eller tilgangsstyring.',
  externalProcessResponsibleDpProcessHelpText: 'Oppgi navn på den behandlingsansvarlige virksomheten.',
  descriptionDpProcessHelpText: 'Beskriv behandlingen NAV gjør på vegne av den behandlingsansvarlige, f.eks. innsamling og lagring av personopplysninger.',
  purposeDpProcessHelpText: 'Beskriv formålet med å bruke personopplysninger i denne behandlingen.',
  article9DpProcessHelpText:
    'Med særlige kategorier personopplysninger menes opplysninger om helse, etnisk opprinnelse, politikk, religion og filosofisk overbevisning, fagforeningsmedlemskap, genetikk og biometri, seksuelle forhold og legning.',
  isSubDataProcessorUsedDpProcessHelpText: 'En underdatabehandler er en virksomhet som behandler personopplysninger på vegne av NAV når NAV selv opptrer som databehandler.',
  retentionMonthsDpProcessHelpText: 'Oppgi lagringstiden NAV er forpliktet til å overholde. Denne skal fremgå av databehandleravtalen med den behandlingsansvarlige.',

  READ: 'Les',
  WRITE: 'Skriv',
  SUPER: 'Super',
  ADMIN: 'Admin',

  CREATE: 'Opprett',
  UPDATE: 'Oppdater',
  DELETE: 'Slett',

  INFORMATION_TYPE: 'Opplysningstype',
  POLICY: 'Opplysningstype i behandling',
  PROCESS: 'Behandling',
  DISCLOSURE: 'Utlevering',
  DOCUMENT: 'Dokument',
  CODELIST: 'Kodeverk',

  INFO: 'Info',
  WARNING: 'Advarsel',
  ERROR: 'Feil',

  MISSING_LEGAL_BASIS: 'Behandlingsgrunnlag er ikke avklart',
  EXCESS_INFO: 'Overskuddsinformasjon',
  MISSING_ARTICLE_6: 'Behandlingsgrunnlag for artikkel 6 mangler',
  MISSING_ARTICLE_9: 'Behandlingsgrunnlag for artikkel 9 mangler',
  USES_ALL_INFO_TYPE: 'Bruker alle opplysningstyper',
  potentialPersonalCategoryUsage: 'Bruker potensielt alle personkategorier',
  organizing: 'Organisering',
  department: 'Avdeling',
  subDepartment: 'Linja',
  subDepartmentShort: 'Linja',
  save: 'Lagre',
  update: 'Oppdater',
  export: 'Eksporter',
  exportInternal: 'Eksport for internt bruk',
  exportExternal: 'Eksport for eksternt bruk',
  exportHeader: 'Velg eksport metode',
  abort: 'Avbryt',
  login: 'Logg inn',
  logout: 'Logg ut',
  hi: 'Hei',
  addNew: 'Legg til ny',
  createNew: 'Opprett ny',
  name: 'Navn',
  email: 'Email',
  copied: 'Kopiert',
  groups: 'Grupper',
  description: 'Beskrivelse',
  additionalDescription: 'Ytterligere beskrivelse',
  additionalDescriptionHelpText:
    'Personvernrelevant informasjon som ikke passer inn i andre felt kan beskrives her. Eksempelvis om man i behandlingen får uønskede personopplysninger gjennom et fritekstfelt o.l.',
  usefulInformation: 'Nyttig å vite om opplysningstypen',
  disclosureName: 'Navn på utlevering',
  document: 'Dokument',
  edit: 'Rediger',
  editInformationTypes: 'Rediger opplysningstyper',
  sources: 'Kilder',
  categories: 'Kategorier',
  keywords: 'Nøkkelord',
  searchWords: 'Søkeord',
  read: 'Lese',
  write: 'Skrive',
  administrate: 'Admin',
  delete: 'Slett',
  appName: 'Behandlingskatalog',
  beta: 'beta',
  all: 'Alle',
  added: 'lagt til',
  addManyFromSystem: 'Legg til flere fra et system',
  level: 'Nivå',
  type: 'Type',
  allProcesses: 'Alle behandlinger',
  completedProcesses: 'Ferdig dokumentert',
  showCompletedProcesses: 'Ferdig dokumenterte behandlinger',
  inProgressProcesses: 'Behandlinger under arbeid',
  filter: 'Filter',
  startDate: 'Fom dato',
  endDate: 'Tom dato',
  inactive: 'Inaktiv',
  active: 'Aktiv',
  preview: 'Forhåndsvisning',
  view: 'Vis',
  info: 'Informasjon',
  ghost: 'Vis bruk',
  version: 'Versjonering',
  period: 'Periode',
  recipient: 'Mottaker',
  slack: 'Slack kanal',
  add: 'Legg til',
  status: 'Status',
  processStatus: 'Status på utfylling',
  processStatusHelpText: '',
  isProcessImplemented: 'Er behandlingen innført i NAV?',
  inProgress: 'Under arbeid',
  done: 'Fullført',
  completed: 'Godkjent',
  incomplete: 'Ufullstendig',
  inProduction: 'I produksjon',
  notInProduction: 'Ikke i produksjon',
  isDpiaRequired: 'Er det behov for PVK?',
  dpiaNeeded: 'Behov for PVK',
  dpiaHelpText: 'Det er behov for å gjøre en PVK dersom det er sannsynlig at behandlingen vil medføre en høy risiko for den registrertes rettigheter og friheter',
  lastModified: 'Sist endret av {0}, {1}',
  fomDateHelpText: 'Fra og med-dato er preutfylt med den datoen NAV ble opprettet. For behandlinger med senere fom-dato, må denne endres. Datoen kan også settes frem i tid.',
  tomDateHelpText: 'Til og med-dato skal kun oppgis dersom behandlingen er midlertidig og har en sluttdato.',
  mailLog: 'Mail log',

  prevButton: 'Forrige',
  nextButton: 'Neste',
  of: 'av',
  rows: 'Rader',

  maxChars: 'Maks {0} tegn',
  required: 'Feltet er påkrevd',
  datePickStart: 'Velg fra og med dato',
  datePickEnd: 'Velg til og med dato',
  dateFormat: 'Feil dato format, eksempel: 2018-08-22',
  useDates: 'Velg datoer',
  pvkRequired: 'Personkonsekvensvurdering (PVK)',

  requiredGdprArt6: 'Opplysningstypen krever et behandlingsgrunnlag med artikkel 6',
  requiredGdprArt9: 'Opplysningstypen krever et behandlingsgrunnlag med artikkel 9',
  requiredLegalBasisForDedicated: 'Ingen behandlingsgrunnlag valgt',
  requiredNationalLaw: 'Artikkelen krever nasjonal lov',
  requiredDescription: 'Artikkelen krever ytterligere beskrivelse',

  code: 'Kode',
  codes: 'Koder',
  shortName: 'Kortnavn',
  createCodeListTitle: 'Ny kode',
  deleteCodeListConfirmationTitle: 'Bekreft sletting',
  editCodeListTitle: 'Rediger kode',
  manageCodeListTitle: 'Administrering av kodeverk',
  chooseCodeList: 'Velg kodeverk',
  createNewCodeList: 'Opprett ny kode',

  dpiaReference: 'Ref. til PVK',
  dpiaReferencePlaceholder: '(f.eks. lenke til Websak, Confluence e.l.)',
  grounds: 'Begrunnelse',
  reference: 'Referanse: ',
  ground: 'Begrunnelse: ',
  pvk: 'Personvernkonsekvensvurdering',
  id: 'Id',
  searchId: 'Søk etter id',
  audit: 'Versjonering',
  audits: 'Versjoneringer',
  auditNr: 'Versjon #',
  auditNotFound: 'Fant ingen versjonering',
  table: 'Tabellnavn',
  action: 'Aksjon',
  time: 'Tidspunkt',
  user: 'Bruker',
  close: 'Lukk',
  filterPieChartsByStatus: 'Filtrer diagrammene på status',
  lastChanges: 'Siste endringer',
  settings: 'Innstillinger',
  revision: 'Revidering',
  needsRevision: 'Trenger revidering',
  revisionCreated: 'Revidering etterspurt',
  newRevision: 'Ny revidering',
  revisionText: 'Revideringstekst',
  completedOnly: 'Bare fullførte',
  back: 'Tilbake',
  one: 'Èn',
  containsInformationType: 'Inneholder opplysningstyper',
  containsProcesses: 'Brukes i behandlinger',
  defaultProcessDocument: 'Dokument for standard informasjonstyper i behandling',
  overallPurposeHelpText: 'Hva er det overordnede formålet med denne behandlingen? Velg blant predefinerte verdier',
  validityOfProcessHelpText:
    'Valgfritt. Hvis aktuelt angi perioden virksomheten har utført denne behandlingen. Kan stå tomt hvis usikkert, eller for løpende behandlinger som f.eks. saksbehandling av diverse ytelser.',
  organizingHelpText:
    'Angi hvilken avdeling som er ansvarlig for behandlingen. Der hvor behandlingen utføres i linja så angi hvor i linja behandlingen utføres. Dersom behandlingen understøttes av IT-systemer, angi hvilke team som har forvaltningsansvaret for systemene.',
  processNameHelpText: 'Et kort navn som beskriver hva behandlingen går ut på. Eksempel: Saksbehandling, håndtere brukerhenvendelser eller rekruttering.',
  processPurposeHelpText:
    'Beskriv formålet med å bruke personopplysninger i denne behandlingen. Eksempel: Behandle og vurdere rett til stønad ved behov for førerhund pga nedsatt syn.',
  departmentHelpText: 'Angi hvilken avdeling som har hovedansvar for behandlingen.',
  productTeamHelpText:
    'Teamet i IT-avdelingen som har ansvaret for IT-løsningen som understøtter denne behandlingen. Ikke aktuelt på alle behandlinger. Eksempel: Team Pensjon, Team Bidrag',
  subDepartmentHelpText: 'Dersom behandlingen utføres i linja, angi hvor i linja behandlingen utføres.',
  systemHelpText: 'Angi hvilke systemer som er primært i bruk i denne behandlingen.',
  usesAllInformationTypesHelpText:
    'Brukes for å angi at denne behandlingen bruker alle opplysningstyper. Brukes derfor kun unntaksvis for noen spesielle behandlinger som f.eks. logginnsyn, innsyn etter personopplysningsloven, behandlinger knyttet til personvernombudet eller Sikkerhetsseksjonens virksomhet.',
  processAutomationHelpText: 'Med helautomatisert behandling menes behandling som fører til en individuell avgjørelser eller vedtak uten menneskelig involvering',
  profilingHelpText: 'Med profilering menes det å utlede nye egenskaper, tilbøyeligheter eller behov hos en bruker etter sammenligning med andre brukere i liknende omstendigheter',
  processorHelpText: 'En databehandler er en virksomhet som behandler personopplysninger på NAVs vegne.',
  processorAgreementHelpText: 'Oppgi referanse (typisk saksnummer) til avtalens lagringssted, for eksempel i Websak.',
  processorOutsideEUExtraHelpText: 'Oppgi om personopplysningene behandles utenfor EU/EØS-området av databehandleren eller eventuelle underdatabehandlere.',
  legalBasisHelpText: 'Oppgi hvilket behandlingsgrunnlag som benyttes for å kunne behandle personopplysningene.',
  retentionHelpText:
    'Oppgi når lagringstiden begynner å løpe. Dette er tidspunktet vi regner lagringsbehovet fra. For eksempel begynner lagringstiden for opplysninger i flere HR-behandlinger å løpe fra ansettelsesforholdets avslutning. Andre eksempler for bruk av personopplysninger om etatens brukere kan være fra søknad mottatt, fødsel, død, søknadens virkningstidspunkt o.l.',
  retentionDescriptionHelpText:
    'Begrunnelse for hvorfor vi har behov for å oppbevare personopplysningene i oppgitt lagringstid. For eksempel kan behovet skyldes at vi må kunne forsvare oss mot rettskrav eller at vi må kunne vurdere mulige krav om tilbakebetaling av feilutbetalt ytelse.',
  retentionNeedsHelpText:
    'Det er hvor lenge NAV har behov for tilgang til opplysningene vi ønsker svar på her. Når den tiden nås skal opplysningene enten kasseres eller gjøres klar for avlevering til Arkivverket.',
  processSideMenuHelpText: 'En aktivitet du gjør på personopplysninger for å oppnå et formål. Eks. på behandling: Saksbehandling av alderspensjon',
  informationTypeSideMenuHelpText: 'Personopplysninger som f.eks. kjønn, sivilstand, pensjonsopptjening.',
  documentSideMenuHelpText: 'En samling av opplysningstyper. Sykmelding og inntektsmelding er eksempler på dokumenter som inneholder flere opplysningstyper.',
  externalPartsSideMenuHelpText: 'Parter utenfor NAV som vi samhandler med. Eksempler er Folkeregisteret, Lånekassen, brukere, arbeidsgivere',
  systemSideMenuHelpText: 'En samling av beslektede applikasjoner som sammen løser et forretningsbehov. F.eks. Pesys, Modia, Aa-reg',
  disclosuresSideMenuHelpText: 'En samling av utleveringer av persondata fra NAV til eksterne bedrifter eller etater',
  processorSideMenuHelpText: 'Her finner du en oversikt over databehandlere',
  dashboard: 'Dashboard',
  dashboardSideMenuHelpText: 'Oversikt og statistikk over behandlinger og andre samlinger i behandlingskatalogen',
  categoryNotInUse: 'Kategori {0} er ikke i bruk',
  excessInfoHelpText: 'Informasjon som er tilgjengelig i dokumenter eller systemet som brukes, uten at dette trengs eller brukes i behandlingen.',
  goToSite: 'Gå til side',
  navResponsible: 'Behandlinger hvor NAV er felles behandlingsansvarlig med ekstern part',

  no_dpia_no_special_category_pi: 'Ingen særlige kategorier personopplysninger behandles',
  no_dpia_small_scale: 'Behandlingen skjer ikke i stor skala (få personopplysninger eller registrerte)',
  no_dpia_no_dataset_consolidation: 'Ingen sammenstilling av datasett på tvers av formål',
  no_dpia_no_new_tech: 'Ingen bruk av teknologi på nye måter eller ny teknologi',
  no_dpia_no_profiling_or_automation: 'Ingen bruk av profilering eller automatisering',
  no_dpia_other: 'Annet',

  chooseGrounds: 'Velg en eller flere begrunnelse(r)',
  specifyOther: 'Spesifiser ved annet',

  missingPVK: 'Ref. til PVK ikke angitt',

  noInformationTypesAvailableInTable: 'Ingen opplysningstyper',
  noCodesAvailableInTable: 'Ingen koder',
  noProcessesAvailableInTable: 'Ingen behandlinger',
  noUsageAvailableInTable: 'Ingen bruk',
  noDocumentsAvailableInTable: 'Ingen dokumenter',
  noPotentialPersonalCategoryUsageInTable: 'Bruker potensielt alle personkategorier',
  usesAllInformationTypes: 'Bruker potensielt alle opplysningstyper',
  noAuditsAvailableInTable: 'Ingen versjoneringer',
  noDisclosuresToThirdPartyAvailableInTable: 'Ingen utlevering',
  noRetrievedFromThirdPartyAvailableInTable: 'Ingen innhentinger fra ekstern part',
  noAlertsAvailableInTable: 'Ingen varsler',
  noAaregContractsAvailableInTable: 'Ingen AA-Reg avtale',
  deliverAbroad: 'Utleveres personopplysningene til utlandet?',
  socialSecurityAgreement: 'Oppgi referanse til trygdeavtale',
  socialSecurityArea: 'Trygdeområde',

  disclosureNameTooltip: 'Et kort navn som beskriver hva utleveringen går ut på. Eksempel: Utlevering av syke- og uføreopplysninger fra NAV til forsikringsselskap.',
  disclosurePurposeTooltip:
    'Beskriv formålet med utleveringen til mottaker. Eksempel: Formålet er å bidra til at forsikringsselskap kan motta opplysninger fra NAV som er nødvendig for å behandle en forsikringssak.',
  disclosureDescriptionTooltip:
    'Relevant informasjon som ikke passer inn i andre felt kan beskrives her. For eksempel hva slags type informasjon som utleveres, regelmessighet eller lignende.',
  disclosureDocumentTooltip: 'En samling av opplysningstyper. Sykmelding og inntektsmelding er eksempel på dokumenter som inneholder flere opplysningstyper.',

  shortcutSubtitleProcess: 'Se og endre behandlinger',
  shortcutSubtitleInformationtype: 'Se og endre opplysningstyper',
  shortcutSubtitleThirdParty: 'Se alle eksterne parter',
  shortcutSubtitleDashboard: 'Se statistikk over behandlinger',
  processorSelect: 'Velg databehandler',
  createProcessor: 'Opprett ny databehandler',
  contract: 'Ref. på databehandleravtale',
  contractOwner: 'Avtaleeier',
  operationalContractManagers: 'Fagansvarlig',
  note: 'Merknad',
  transferPanelTitle: 'Overføres data til utlandet',
  mainPageMessage: 'Hva vil du gjøre?',
  mainPageEventsMessage: 'Hva har endret seg i det siste?',
  notFoundProcessor: 'Databehandler er ikke registrert i løsningen. Registrer databehandleren først.',
  notFoundDisclosure: 'Ingen eksisterende utleveringer matcher søket. Opprett ny utlevering før du legger den til her.',
  processorName: 'Navn på databehandler',
  processorNameHelpText: ' Navn på databehandler.',
  contractHelpText: 'Referanse til avtalen, gjerne URL til avtalen i WebSak e.l. ',
  contractOwnerHelpText: 'Den som formelt står som eier av avtalen med databehandler.',
  operationalContractManagersHelpText: 'De(n) som kan svare ut detaljer knyttet til avtalen og operasjonalisering av denne.',
  noteHelpText: 'Eventuelle vesentlige merknader/begrensninger som bruker av databehandleren må være ekstra oppmerksom på.',
  transferGroundsOutsideEUEEAHelpText: 'I tilfeller hvor databehandler behandler personopplysninger utenfor EU/EØS, hva er overføringsgrunnlaget?',
  transferGroundsOutsideEUEEAOtherHelpText: 'Du har valgt at overføringsgrunnlaget er "annet", spesifiser grunnlaget her.',
  countriesHelpText: 'I hvilke(t) land lagrer databehandleren personopplysninger i?',
  isDataProcessedOutsideEUEEAHelpTextDP: 'Angi om databehandler overfører/behandler personopplysninger i land utenfor EU/EØS.',
  canNotDeleteProcessorParagraph1: 'Kan ikke slette databehandleren {0} da den er',
  canNotDeleteProcessorParagraph2: 'knyttet til {0} behandling(er)',
  deleteProcessDisclosureError: 'Du kan ikke slette behandlinger med eksisterende utleveringer.',
  administrationArchiveCaseNumber: 'Saksnummer i adminstrativt arkiv',
  moreInfo: 'Mer informasjon finner du',
  here: 'her',
  supervisor: 'Veileder',
  omBehandlingskatalog: 'Veileder til Behandlingskatalogen',
  confidentialityAssessment: 'Hjemmel for unntak fra taushetsplikt er vurdert',
  confidentialityDescriptionYes: 'Hjemmel for unntak fra taushetsplikt, og ev. referanse til vurderingen',
  confidentialityDescriptionNo: 'Begrunnelse for at hjemmel for unntak for taushetsplikt ikke er vurdert'
}

export const en: IStrings = {
  //aareg avtale
  aaregContracts: 'Disclosure contracts from Aa-registry',
  organisationNumber: 'Organisation number',
  aaregContractNumber: 'Contract number',
  showAaregTable: 'Show Aa-reg avtaler',
  hideAaregTable: 'Hide Aa-reg avtaler',
  createdDate: 'Created date',
  accessType: 'Access type',
  API: 'API',
  extract: 'Extract',
  webLookup: 'Web lookup',
  incidents: 'Incidents',
  consumer: 'Consumer',
  contractAareg: 'Contract',
  purposeForProcess: 'Purpose for process',
  authorityAndGroundsForDelivery: "NAV's authority for disclosure",
  consumerAuthorityForProcess: "Consumer's authority for process",
  purposeAuthorityLegalBasis: 'Purpose, authority and legal basis',
  available: 'Available',
  unavailable: 'Unavailable',

  informationType: 'Information type',
  informationTypes: 'Information types',
  informationTypeSearch: 'Information type search',
  search: 'Search',
  term: 'Term definition',
  termEditHeader: 'Term definition (lookup in Term Catalog)',
  purpose: 'Purpose',
  processPurpose: 'Process purpose',
  processNumber: 'Process number',
  purposeOfTheProcess: 'Purpose of the process',
  purposeDescription: 'General purpose description',
  sensitivity: 'Type of personal data',
  processingActivities: 'Processing activities',
  process: 'Process',
  dpProcess: 'Data Process',
  dpProcesses: 'Data Processes',
  processes: 'Processes',
  orgMaster: 'Master in NAV',
  orgMasterInfTypeHeader: 'Information types mastered by the system',
  legalBasis: 'Legal basis for process',
  legalBasisShort: 'Legal basis',
  legalBasesShort: 'Legal bases',
  nationalLaw: 'National law',
  gdprArticle: 'GDPR Article',
  subjectCategories: 'Subject categories',
  summarySubjectCategories: 'Summary subject categories',
  processContainsSubjectCategory: "The process already contains subject category '{0}' for information type '{1}'",
  productTeam: 'Team',
  productTeamFromTK: 'Team (lookup in in Team Catalog)',
  productTeamFromTKHelpText: 'Specify which teams are responsible for managing IT systems.',
  product: 'Product',
  products: 'Products',
  team: 'Team',
  productArea: 'Product area',
  system: 'System',
  systems: 'Systems',
  disclosure: 'Disclosure',
  disclosures: 'Disclosures',
  dispatcher: 'Dispatcher',
  linkDisclosurePage: 'Link to disclosure page',
  editDisclosure: 'Edit disclosure',
  documents: 'Documents',
  dataAccessClass: 'Data access class',
  dataAccessClassSelect: 'Select data access class',
  thirdParty: 'Third party',
  thirdParties: 'Third parties',
  alerts: 'Alerts',
  policy: 'Policy',
  usage: 'Usage',
  and: 'and',
  with: 'with',
  pollyOrg: 'NAV',
  or: 'or',
  remove: 'Remove',
  yes: 'Yes',
  no: 'No',
  seeExternalLink: 'See external link',
  done: 'Done',
  filterPieChartsByStatus: 'Filter diagrams by status',
  processActivity: 'Process activity',
  aboutUs: 'About process catalog',
  includeConservationPlan: "Is NAV's conservation and disposal decision covered?",
  unclarified: 'Unclarified',
  unknown: 'Unknown',
  notFilled: 'Not filled',
  filled: 'Filled',
  automation: 'Automation and profiling',
  automaticProcessing: 'Automatic Processing',
  isAutomationNeeded: 'Is decision made based on fully automated process?',
  automaticProcessingExtra: 'Is a decision made based on fully automated processing of personal data? In other words, decisions that are made without human involvement.',
  profiling: 'Profiling',
  isProfilingUsed: 'Is profiling used?',
  profilingExtra:
    "By profiling we mean that personal data is processed automatically in order to analyze or predict something about the preferences, abilities or needs of an individual. Analyzing personal data is done to predict something about an individual, e.g. the person's preferences, abilities or needs.",
  processor: 'Processor',
  processors: 'Processors',
  dpProcessDataProcessor: 'Processor agreement with data controller',
  subDataProcessor: 'Sub processor',
  isProcessorUsed: 'Is processor used?',
  isSubDataProcessorUsed: 'Is sub processor used?',
  processorYes: 'Processor is used',
  dpProcessProcessorYes: 'Processing Agreement signed',
  processorNo: 'Processor is not used',
  dpProcessDataProcessorNo: 'Data Processing Agreement not signed',
  processorUnclarified: 'Unclarified wether processor is used',
  dpProcessDataProcessorUnclarified: 'Unclarified Data Processing Agreement',
  processorExtra: 'Is a processor used to perform the processing of personal data',
  processorAgreement: 'Ref. to processor agreement',
  processorAgreementPlaceholder: '(i.e. link to Websak, Confluence etc.)',
  processorOutsideEU: 'Outside EU / EEA',
  isDataProcessedOutsideEUEEA: 'Does process data processed outside of EU/EEA?',
  isSubDataProcessedOutsideEUEEA: 'Does sub process data processed outside of EU/EEA?',
  isDataProcessedOutsideEUEEAHelpText: 'Personal data processed outside EU/EEA',
  transferGroundsOutsideEUEEA: 'Transfer grounds for processing outside of EU/EEA',
  transferGroundsOutsideEUEEAOther: 'Other grounds',
  countries: 'Countries',
  includeDefaultDocument: 'Default information types',
  riskOwner: 'Risk owner',
  riskOwnerFunction: 'Risk owner function',
  riskOwnerFunctionBinder: 'in function of',
  commonExternalProcessResponsible: 'Common process responsible',
  commonExternalProcessResponsibleHelpText: 'Is the NAV responsible for the process with another business?',
  from: 'from',
  retained: 'Retained',
  retention: 'Retention needs',
  processWithIncompleteRetention: 'Process with incompleted retention: ',
  retentionPlan: "Is the area covered by the agency's disposal and conservation decision?",
  retentionPlanYes: "Covered by the NAV's disposal and conservation decision",
  retentionPlanNo: "Not covered by the NAV's disposal and conservation decision",
  retentionPlanUnclarified: "Unclarified whether covered by the NAV's disposal and conservation decision",
  retentionMonths: 'Retention needs for NAV',
  retentionStart: 'Retention needs are calculated from the following time or event',
  retentionDescription: 'Retention grounds',
  retentionDescriptionPlaceHolder: '(i.e. link to Websak, Confluence etc.)',
  retentionReference: 'Ref. to relevant documentation',
  retentionPieChartTitle: "Includes NAV's disposal and conservation decision",
  years: 'years',
  months: 'months',
  lastEvents: 'Last events',
  userLastChanges: 'My last changes',
  help: 'Help',
  helpTooltip: "On the hub's privacy pages you will find information to help you fill it out.",
  navResponsible: 'Processes which NAV is jointly responsible for processing with an external party',
  exceptionalUsage: 'Exceptional usage',
  overallPurpose: 'Overall purpose',
  overallPurposeActivity: 'Overall process activity',
  containsInformationType: 'Contains information type(s)',
  containsProcesses: 'Used in information type(s)',
  loggedInStatus: 'You are logged in and can',
  notLoggedInStatus: 'You are not logged in but you can still',
  couldntLoad: "Couldn't load the page",
  couldntLoadTerm: "Couldn't load the term",
  noTerm: 'No term given',
  couldntLoadTeam: "Couldn't load the team",
  informationTypeCreate: 'Create new information type',
  informationTypeExists: 'Information type exists already',
  documentExists: 'Document with the same name already exists',
  sensitivitySelect: 'Select type of personal data',
  nameWrite: 'Enter name',
  categoriesWrite: 'Enter and add categories',
  sourcesWrite: 'Enter and add sources',
  keywordsWrite: 'Enter and add keywords',
  searchWordsWrite: 'Enter and add search words',
  orgMasterSelect: 'Select master',
  purposeSelect: 'Select overall process activity',
  purposeNotFound: 'Found no purposes',
  processingActivityUse: 'Used for processing activities',
  informationTypeExternalUse: 'External use',
  policyEdit: 'Edit purpose for information type',
  policyNew: 'Create new process for information type',
  policyAdd: 'Add information type to process',
  processNew: 'Add new process',
  processCreated: 'Process created',
  doYouWantToAddPolicies: 'Do you want to add information types?',
  addPolicies: 'Add information types one by one',
  addDefaultDocument: 'Add standard information types',
  legalBasisNotFound: 'Found no legal bases',
  processEdit: 'Edit process for information type',
  processingActivitiesNew: 'Create new processing activity',
  processingActivitiesEdit: 'Edit processing activity',
  legalBasisNew: 'Legal basis',
  legalBasisAdd: 'Add new legal basis',
  article6HelpText: 'All processing of personal data requires a legal basis according to Article 6 of the Personal Data Act.',
  article9HelpText: 'All processing of special categories (sensitive) of personal data also requires a legal basis in accordance with the Personal Data Act, Article 9.',
  addArticle6: 'Legal basis (Article 6)',
  addArticle9: 'Legal basis for special categories (Article 9)',
  cardHeaderArticle6: 'Legal basis (Article 6)',
  cardHeaderArticle9: 'Legal basis for special categories (Article 9)',
  placeHolderArticle6: 'Select article 6',
  placeHolderArticle9: 'Select article 9',
  numberOfProcessesWithUnknownLegalBasis: 'Processes with unknown legal basis',
  numberOfProcessesWithoutArticle6LegalBasis: 'Processes without article 6',
  numberOfProcessesWithoutArticle9LegalBasis: 'Processes without article 9',
  withoutArticle6LegalBasisHelpText: 'All processing of personal data must have a legal basis in accordance with Article 6 of the Personal Data Act',
  withoutArticle9LegalBasisHelpText:
    'Processing of personal data considered as special categories (formerly sensitive information) requires a further processing basis in accordance with the Personal Data Act Art. 9',
  unknownLegalBasisHelpText: 'All processing of personal data must have a legal basis in accordance with Article 6 of the Personal Data Act',
  processesWithUnknownLegalBasis: 'Processes with unknown legal basis',
  processesWithoutArticle6LegalBasis: 'Processes without article 6',
  processesWithoutArticle9LegalBasis: 'Processes without article 9',
  incompleteLegalBasis: 'Processes with incomplete legal basis',
  gdprSelect: 'Select GDPR article',
  nationalLawSelect: 'Select national law',
  descriptionWrite: 'Enter description',
  descriptionWriteLegalBasesF: 'Specify the interest',
  descriptionWriteLegalBasesCE: 'Enter law reference',
  definitionWrite: 'Search definitions',
  subjectCategoriesNotFound: 'Found no subject categories',
  legalBasesProcess: 'Use legal bases from process',
  legalBasesUndecided: 'Undecided',
  legalBasesOwn: 'Use explicit legal bases',
  notAllowedMessage: "You don't have access to this page",
  confirmDeleteHeader: 'Confirm delete',
  confirmDeletePolicyText: 'Please confirm deleting the policy for',
  deleteProcessText: 'Are you sure you want to delete the process? If the process has been discontinued, it should instead be marked with the end date of the process.',
  deleteProcessorText: 'Are you sure you want to delete the processor?',
  confirmDeleteProcessText: 'Please confirm deleting the process ',
  confirmDeleteProcessorText: 'Please confirm deleting the processor ',
  confirmDeleteDocumentText: 'Please confirm deleting the document ',
  confirmDeleteDpProcess: 'Please confirm deleting the document data process',
  cannotDeleteProcess: "Can't delete the process {0} as it contains {1} information type(s)",
  confirmDeleteInformationTypeText: 'Please confirm deleting the of information type ',
  cannotDeleteInformationTypes: "Can't delete the information type {0} as it is",
  informationTypeHasPolicies: ' connected to {0} process(es)',
  informationTypeHasDocuments: ' connected to {0} document(s)',
  startIllustration: 'Process illustration',
  treasureIllustration: 'Treasure illustration',
  legalbasisGDPRArt9Info: 'Informationtypes that are special categories require art. 9',
  legalBasisInfo: 'For Article 6(c, e and f), further specification is needed.',
  disclosureSelect: 'Select thirdparty',
  groupByProcessingActivities: 'Group by processing activities',
  showAll: 'Show all',
  createThirdPartyModalTitle: 'Create disclosure for a thirdparty',
  disclosuresToThirdParty: 'Disclosures to',
  retrievedFromThirdParty: 'Retrieved from thirdparties',
  usageNotFound: 'No usage found',
  newValue: 'New Value',
  replace: 'Replace',
  replaceAllUse: 'Replace all use',
  recipientPurpose: "Recipient's purpose",
  legalBasisComplete: 'Close legal basis editor before saving',
  validityOfProcess: 'Validity of process',
  validityOfPolicy: 'Validity of policy',
  chooseDocument: 'Select document a document to start',
  addDocument: 'Add information types from dokument',
  searchDocuments: 'Search documents',
  searchProcess: 'Search processes',
  addOneInformationType: 'Add one information type',
  addCollectionOfInformationTypes: 'Add a collection of information types',
  emptyTable: 'No',
  emptyMessage: 'Not filled',
  pageNotFound: "Oops 404! Couldn't find that page",
  createDocument: 'Create document',
  searchDocumentPlaceholder: 'Search documents',
  eventType: 'Event type',
  disclosurePurpose: 'Purpose for disclosure',
  departmentSelect: 'Select department',
  subDepartmentSelect: 'Select subdepartment',
  teamSelect: 'Select team',
  informationtypesUsedInDocument: 'Information types used in document',
  editDocument: 'Edit document',
  status: 'Status',
  processStatus: 'Process documentation status',
  processStatusHelpText: '',
  isProcessImplemented: 'Is process implemented in NAV?',
  inProduction: 'In production',
  notInProduction: 'Not in production',
  isDpiaRequired: 'Is DPIA required?',
  dpiaNeeded: 'Need for DPIA',
  dpiaHelpText: "It is necessary for DPIA assessment if there is probable that the process will entail a high risk of the data's rights and freedoms.",
  lastModified: 'Last modified by {0}, {1}',
  completeness: 'Completeness',
  overview: 'Overview',
  dpProcessTitle: 'Data process',
  dpProcessPageTitle: 'Processes which are being process by NAV',
  thirdPartyDpProcessTableTitle: 'Nav is processor for {0} in following processors',
  article9: 'Are special categories of personal data processed?',
  article10: 'Is personal data about criminal convictions and offenses processed?',
  createDpProcess: 'Create new process',
  dpProcessDuplicatedError: 'Data process has already exist.',
  externalProcessResponsible: 'Process responsible',
  relatedProcesses: 'Related processes',
  frontPageStartMessage: 'Choose your path!',

  nameDpProcessHelpText: 'A short name that states what the process is about. Examples: case management or access control',
  externalProcessResponsibleDpProcessHelpText: 'State the name of the party responsible for this process',
  descriptionDpProcessHelpText: 'Describe the processes NAV does on behalf of the process responsible party, i.e. collecting and storing personal information',
  purposeDpProcessHelpText: 'Describe the purpose of using personal information in this process',
  article9DpProcessHelpText:
    'With special categories of personal information means information about health, ethnic origin, politics, religion and philosophical beliefs, trade union membership, genetics and biometrics, sexual relations and orientation.',
  isSubDataProcessorUsedDpProcessHelpText: "A sub processor is a party that processes personal data on NAV's behalf when NAV itself acts as the processor",
  retentionMonthsDpProcessHelpText: 'Specify the retention time NAV is obliged to comply. The retention time must be specified in the processor agreement',

  READ: 'Read',
  WRITE: 'Write',
  SUPER: 'Super',
  ADMIN: 'Admin',

  CREATE: 'Create',
  UPDATE: 'Update',
  DELETE: 'Delete',

  INFORMATION_TYPE: 'Information type',
  POLICY: 'Information type in process',
  PROCESS: 'Process',
  DISCLOSURE: 'Disclosure',
  DOCUMENT: 'Document',
  CODELIST: 'Codelist',

  INFO: 'Info',
  WARNING: 'Warning',
  ERROR: 'Error',

  MISSING_LEGAL_BASIS: 'Legal bases missing',
  EXCESS_INFO: 'Excess info',
  MISSING_ARTICLE_6: 'Legal basis for article 6 is missing',
  MISSING_ARTICLE_9: 'Legal basis for article 9 is missing',
  USES_ALL_INFO_TYPE: 'Uses all information type',
  potentialPersonalCategoryUsage: 'Potentially uses all personal categories',

  organizing: 'Organizing',
  department: 'Department',
  subDepartment: 'Sub department',
  subDepartmentShort: 'Sub dep.',
  save: 'Save',
  update: 'Update',
  export: 'Export',
  exportInternal: 'Export for internal use',
  exportExternal: 'Export for external use',
  exportHeader: 'Choose export method',
  abort: 'Cancel',
  login: 'Login',
  logout: 'Logout',
  hi: 'Hi',
  addNew: 'Add new',
  createNew: 'Create new',
  name: 'Name',
  email: 'Email',
  copied: 'Copied',
  groups: 'Groups',
  description: 'Description',
  additionalDescription: 'Additional description',
  additionalDescriptionHelpText:
    'Privacy-relevant information that does not fit into other fields can be described here. For example, if you receive unwanted personal information in the process through a free text field etc.',
  usefulInformation: 'Useful information about information type',
  disclosureName: 'Disclosure name',
  document: 'Document',
  edit: 'Edit',
  editInformationTypes: 'Edit information types',
  sources: 'Sources',
  categories: 'Categories',
  keywords: 'Keywords',
  searchWords: 'Search word',
  read: 'Read',
  write: 'Write',
  administrate: 'Admin',
  delete: 'Delete',
  appName: 'Process catalog',
  beta: 'beta',
  all: 'All',
  added: 'added',
  addManyFromSystem: 'Add several from a system',
  level: 'Level',
  type: 'Type',
  allProcesses: 'All processes',
  completedProcesses: 'Completed processes',
  showCompletedProcesses: 'Completed processes',
  inProgressProcesses: 'In progress processes',
  filter: 'Filter',
  startDate: 'Start date',
  endDate: 'End date',
  inactive: 'Inactive',
  active: 'Active',
  recipient: 'Recipient',
  slack: 'Slack channel',
  preview: 'Preview',
  view: 'View',
  ghost: 'Usage',
  info: 'Info',
  period: 'Period',
  useDates: 'Use dates',
  pvkRequired: 'Need for personal impact assessment (PIA)',
  version: 'Version',
  add: 'Add',
  inProgress: 'In progress',
  completed: 'Completed',
  incomplete: 'Incomplete',
  fomDateHelpText: 'The start date is pre-filled with the date NAV was created. For treatments with a later date, this must be changed. The date can also be set ahead of time.',
  tomDateHelpText: 'This should only be stated if treatment is temporary and has an end date.',
  mailLog: 'Mail log',

  prevButton: 'Prev',
  nextButton: 'Next',
  of: 'of',
  rows: 'Rows',

  maxChars: 'Max {0} characters',
  required: 'Field is required',
  dateFormat: 'Incorrect date format, ex: 2018-08-22',
  datePickEnd: 'Select to date (inclsuive)',
  datePickStart: 'Select from date (inclusive)',

  requiredGdprArt6: 'The information type requires a legal basis for article 6',
  requiredGdprArt9: 'The information type requires a legal basis for article 9',
  requiredLegalBasisForDedicated: 'No legal bases selected',
  requiredNationalLaw: 'The article requires national law',
  requiredDescription: 'The article requires additional description',

  code: 'Code',
  codes: 'Codes',
  shortName: 'Short name',
  createCodeListTitle: 'Create code',
  deleteCodeListConfirmationTitle: 'Confirm deletion',
  editCodeListTitle: 'Edit code',
  manageCodeListTitle: 'Manage code lists',
  chooseCodeList: 'Choose code list',
  createNewCodeList: 'Create new code',

  dpiaReference: 'DPIA Reference',
  dpiaReferencePlaceholder: '(i.e. link to Websak, Confluence etc.)',
  grounds: 'Grounds',
  reference: 'Reference: ',
  ground: 'Ground: ',
  pvk: 'Data Protection Impact Assessment',
  id: 'Id',
  searchId: 'Search for id',
  audit: 'Audit',
  audits: 'Audits',
  auditNr: 'Audit #',
  auditNotFound: 'No audits found',
  table: 'Table name',
  action: 'Action',
  time: 'Time',
  user: 'User',
  close: 'Close',
  lastChanges: 'Last changes',
  settings: 'Settings',
  revision: 'Revision',
  needsRevision: 'Needs revision',
  revisionCreated: 'Revision requested',
  newRevision: 'New revision',
  revisionText: 'Revision text',
  completedOnly: 'Completed only',
  back: 'Back',
  one: 'One',
  overallPurposeHelpText: 'What is the overall purpose for this process? Choose from predefined values.',
  validityOfProcessHelpText:
    'Optional. If applicable, specify the period in which the business performed this processing. Can be left blank if you are unsure, or for ongoing processes such as case processing of various benefits.',
  organizingHelpText:
    'Specify which department is responsible for the process. If applicable,  indicate where in the organization the process is performed. If the process is supported by IT systems, indicate which teams have the reponsibility for those systems.',
  defaultProcessDocument: 'Document for the default information types in a process',
  processNameHelpText: 'A short and descriptive name that states what the process is about. Examples: case management, handling user inquiries or recruitment.',
  processPurposeHelpText:
    'What is the purpose of using personal data in this process? Need only to be used if you need to describe a more detailed purpose than the high level purpose. Not mandatory.',
  departmentHelpText: 'State which department has responsible for the process.',
  productTeamHelpText: 'The team responsible for the IT solutions that supports this process. Not applicable to all processes. ',
  subDepartmentHelpText: 'If processing is performed in-line, specify where in-line processing is performed.',
  systemHelpText: 'Indicate which IT systems are primarily used in this process',
  usesAllInformationTypesHelpText:
    'Used to indicate that this process uses all information type. Therefore, it is only used exceptionally for some special processes such as. access to Personal Data Act.',
  processAutomationHelpText: 'Fully automated process means process leads to an individual decision or decision without human involvement',
  profilingHelpText: 'By profiling is meant to derive new characteristics, inclinations or needs of a user after comparison with other users in similar circumstances',
  processorHelpText: "A processor is a business that processes personal data on NAV's behalf.",
  processorAgreementHelpText: "Provide reference (i.e. case number) to the contract's storage location.",
  processorOutsideEUExtraHelpText: 'Specify whether personal data is processed outside the EU / EEA area by the processor or any sub-processors.',
  legalBasisHelpText: 'Provide the legal basis used to process personal data.',
  retentionHelpText:
    'Specify when retention time starts to run. The calculation of retention period starts from this point. I.e. the retention time for information used in many HR processes start from the end of employment or from start of employment. ',
  retentionDescriptionHelpText:
    'Reasons why we need to keep personal data in stated storage time. I.e. the need may be because we need to be able to defend ourselves against future legal claims. ',
  retentionNeedsHelpText:
    'How long does NAV need access to the data. When that time is reached, the information must either be discarded or made ready for submission to Arkivverket',
  processSideMenuHelpText: 'An activity that you do on personal data to achieve a purpose. Eg on processing: Case management of retirement pension',
  informationTypeSideMenuHelpText: 'Personal information such as gender, marital status, pension benefits.',
  documentSideMenuHelpText: 'A collection of information types. Sick leave and income message are examples of documents containing multiple types of information.',
  externalPartsSideMenuHelpText: 'Parties outside the NAV that we interact with. Examples are the National Register, the Loan Fund, users, employers',
  systemSideMenuHelpText: 'A collection of related applications that together solve a business need. For example, Pesys, Modia, Aa-reg',
  disclosuresSideMenuHelpText: 'A collection of external organizations that NAV exchanges data with',
  processorSideMenuHelpText: 'A collection of processors',
  dashboard: 'Dashboard',
  dashboardSideMenuHelpText: 'Overview for statistics related to processes and other collections in the process catalog',
  excessInfoHelpText: 'Information that is available in the documents or the system being used, without this being needed or used in processing.',

  goToSite: 'Go to site',
  categoryNotInUse: 'Category {0} is not in use',

  no_dpia_no_special_category_pi: 'No special categories of personal data are processed',
  no_dpia_small_scale: 'The processing does not take place on a large scale (get personal information or registered)',
  no_dpia_no_dataset_consolidation: 'No cross-purpose data set compilation',
  no_dpia_no_new_tech: 'No use of technology in new ways or new technology',
  no_dpia_no_profiling_or_automation: 'No use of profiling or automation',
  no_dpia_other: 'Other',

  chooseGrounds: 'Choose a reason',
  specifyOther: 'Specify by other',

  missingPVK: 'Ref. To PVK not specified',

  noInformationTypesAvailableInTable: 'No information types',
  noCodesAvailableInTable: 'No codes',
  noProcessesAvailableInTable: 'No processes',
  noUsageAvailableInTable: 'No usage',
  noDocumentsAvailableInTable: 'No documents',
  noPotentialPersonalCategoryUsageInTable: 'Potentially uses all personal categories',
  usesAllInformationTypes: 'Potensially uses all informationtypes',
  noAuditsAvailableInTable: 'No audit',
  noDisclosuresToThirdPartyAvailableInTable: 'No disclosure to third parties',
  noRetrievedFromThirdPartyAvailableInTable: 'No retrieved from thirdParty',
  noAlertsAvailableInTable: 'No alerts',
  noAaregContractsAvailableInTable: 'Ingen AA-Reg contracts',
  socialSecurityArea: 'Social security area',
  deliverAbroad: 'Is the personal information disclosed abroad?',
  socialSecurityAgreement: 'Provide reference to social security agreement',

  disclosureNameTooltip: 'A short name that describe what the disclosure is about. Example: Disclosure of sickness and disability information from NAV to an insurance company',
  disclosurePurposeTooltip:
    'Describe the purpose of the disclosure to the recipient. Example: The purpose is to help insurance companies to receive information from NAV that is necessary to process an insurance case',
  disclosureDescriptionTooltip:
    'Relevant information that does not fit into other fields can be described here. For example, what type of information is provided, regularity or similar.',
  disclosureDocumentTooltip: 'A collection of information types. Sick leave and income statement are examples of documents that contain several types of information.',

  shortcutSubtitleProcess: 'See and edit processes',
  shortcutSubtitleInformationtype: 'See and edit informationtypes',
  shortcutSubtitleThirdParty: 'See all third parties',
  shortcutSubtitleDashboard: 'See statistics of processes',
  processorSelect: 'Select processor',
  createProcessor: 'Create new processor',
  contract: 'Data processor reference',
  contractOwner: 'Agreement owner',
  operationalContractManagers: 'Subject manager',
  note: 'Note',
  transferPanelTitle: 'Transfer data to abroad',
  mainPageMessage: 'What do you want to do?',
  mainPageEventsMessage: 'What has changed lately?',
  notFoundDisclosure: 'Disclosure is not registered. Create a new disclosure before adding it here.',
  notFoundProcessor: 'Processor is not registered in the solution. Register the processor first.',
  processorName: 'Processor name',
  processorNameHelpText: 'Processor name.',
  contractHelpText: 'Reference to the agreement, preferably URL to the agreement in WebSak or similar',
  contractOwnerHelpText: 'The person who formally owns the agreement with the data processor.',
  operationalContractManagersHelpText: 'Those who can respond to details related to the agreement and its operationalization.',
  noteHelpText: 'Any significant remarks/restrictions that the user of the data processor must pay extra attention to.',
  transferGroundsOutsideEUEEAHelpText: 'In cases where the data processor processes personal data outside the EU/EEA, what is the transfer grounds?',
  transferGroundsOutsideEUEEAOtherHelpText: 'You have chosen that the transfer grounds is "other", specify it here.',
  countriesHelpText: 'In which country(ies) does the data processor store personal information?',
  isDataProcessedOutsideEUEEAHelpTextDP: 'Indicate whether the data processor transfers/processes personal data in countries outside the EU/EEA.',
  canNotDeleteProcessorParagraph1: 'Can not delete processor {0} because it is',
  canNotDeleteProcessorParagraph2: 'used in {0} processes',
  deleteProcessDisclosureError: 'You can not delete a process with disclosures.',
  administrationArchiveCaseNumber: 'Administration Archive Case Number',
  moreInfo: 'You can find more information',
  here: 'here',
  supervisor: 'Supervisor',
  omBehandlingskatalog: 'Guide to the Behandling',
  confidentialityAssessment: 'Grounds for exemption from confidentiality have been assessed',
  confidentialityDescriptionYes: 'Authority for exemption from confidentiality, and possibly reference to the assessment',
  confidentialityDescriptionNo: 'Justification for the grounds for exceptions to the duty of confidentiality not being considered'
}

export const ta = {
  ADMIN: 'நிர்வாகம்',
  READ: 'படிக்க',
  WRITE: 'எழுது',
  all: 'அனைத்து',
  appName: 'செயல்முறை பட்டியல்',
  beta: 'பீட்டா',
  confirmDeletePolicyHeader: 'நீக்கு என்பதை உறுதிப்படுத்தவும்',
  confirmDeletePolicyText: 'இதற்கான கொள்கையை நீக்குவதை உறுதிப்படுத்தவும்',
  delete: 'அழி',
  email: 'மின்னஞ்சல்',
  endDate: 'கடைசி தேதி',
  groups: 'குழுக்கள்',
  inactive: 'செயல்படா',
  maxChars: 'அதிகபட்ச {0} எழுத்துக்கள்',
  nextButton: 'அடுத்த',
  notAllowedMessage: '',
  prevButton: 'முந்தைய',
  processes: 'செயல்முறைகள்',
  required: 'தேவையான',
  rows: 'வரிசைகள்',
  startDate: 'தொடக்க தேதி',

  informationType: 'தகவல் வகை',
  informationTypes: 'தகவல் வகைகள்',
  informationTypeSearch: 'தகவல் வகை தேடல்',
  term: 'கால வரையறை',
  purpose: 'நோக்கம்',
  sensitivity: 'உணர்திறன்',
  processingActivities: 'செயலாக்க செயல்பாடு',
  process: 'செயல்முறை',
  orgMaster: 'மாஸ்டர் NAV',
  legalBasis: 'செயல்முறைக்கு சட்டபூர்வமான அடிப்படை',
  legalBasisShort: 'சட்ட அடிப்படையில்',
  legalBasesShort: 'சட்ட தளங்கள்',
  nationalLaw: 'தேசிய சட்டம்',
  subjectCategories: 'பொருள் வகைகள்',

  loggedInStatus: 'நீங்கள் உள்நுழைந்துள்ளீர்கள், முடியும்',
  notLoggedInStatus: 'நீங்கள் உள்நுழைந்திருக்கவில்லை, ஆனால் நீங்கள் இன்னும் முடியும்',
  couldntLoad: 'பக்கத்தை ஏற்ற முடியவில்லை',
  informationTypeCreate: 'புதிய தகவல் வகையை உருவாக்கு',
  sensitivitySelect: 'தனிப்பட்ட தரவின் வகையைத் தேர்ந்தெடுக்கவும்',
  nameWrite: 'பெயரை உள்ளிடுக',
  categoriesWrite: 'வகைகளை உள்ளிட்டு சேர்க்கவும்',
  sourcesWrite: 'மூலங்களை உள்ளிட்டு சேர்க்கவும்',
  keywordsWrite: 'முக்கிய வார்த்தைகளை உள்ளிட்டு சேர்க்கவும்',
  orgMasterSelect: 'மாஸ்டரைத் தேர்ந்தெடு',
  purposeSelect: 'நோக்கத்தைத் தேர்ந்தெடு',
  purposeNotFound: 'எந்த நோக்கங்களும் இல்லை',
  purposeUse: 'நோக்கங்களுக்காகப் பயன்படுத்தப்படுகிறது',
  policyEdit: 'தகவல் வகைக்கான நோக்கத்தைத் திருத்து',
  policyNew: 'தகவல் வகைக்கு புதிய செயல்முறையை உருவாக்கு',
  processNew: 'புதிய செயல்முறையைச் சேர்',
  legalBasisNotFound: 'சட்ட தளங்கள் எதுவும் இல்லை',
  processEdit: 'தகவல் வகைக்கான செயல்முறையைத் திருத்து',
  processingActivitiesNew: 'புதிய செயலாக்க செயல்பாட்டை உருவாக்கு',
  processingActivitiesEdit: 'செயலாக்க செயல்பாட்டைத் திருத்து',
  legalBasisNew: 'புதிய சட்ட அடிப்படை',
  legalBasisAdd: 'புதிய சட்ட அடிப்படையைச் சேர்',
  gdprSelect: 'ஜிடிபிஆர் கட்டுரையைத் தேர்ந்தெடுக்கவும்',
  nationalLawSelect: 'தேசிய சட்டத்தைத் தேர்ந்தெடு',
  descriptionWrite: 'விளக்கத்தை உள்ளிடுக',
  definitionWrite: 'வரையறையை உள்ளிடுக',
  subjectCategoriesNotFound: 'பொருள் வகைகள் எதுவும் இல்லை',
  legalBasesProcess: 'செயல்முறையிலிருந்து சட்ட தளங்களைப் பயன்படுத்துங்கள்',
  legalBasesUndecided: 'தீர்மானிக்கப்படாதது',
  legalBasesOwn: 'வெளிப்படையான சட்ட தளங்களைப் பயன்படுத்துங்கள்',
  legalBasesUndecidedWarning: 'சட்ட தளங்கள் இல்லை',

  department: 'துறை',
  subDepartment: 'துணைத் துறை',
  save: 'சேமி',
  abort: 'ரத்துசெய்',
  login: 'உள்நுழை',
  logout: 'வெளியேறு',
  hi: 'ஹாய்',
  addNew: 'புதியதைச் சேர்',
  createNew: 'புதியதை உருவாக்கு',
  name: 'பெயர்',
  description: 'விளக்கம்',
  edit: 'திருத்து',
  sources: 'ஆதாரங்கள்',
  categories: 'வகைகள்',
  keywords: 'சொற்கள்',
  read: 'படிக்க',
  write: 'எழுது',
  administrate: 'நிர்வாகி',
}
