import { IStrings } from "./intl";

export const no: IStrings = {
  informationType: "Opplysningstype",
  informationTypes: "Opplysningstyper",
  informationTypeSearch: "Søk opplysningstyper",
  term: "Begrepsdefinisjon",
  purpose: "Formål",
  processPurpose: "Behandlingsformål",
  purposeDescription: "Overordnet formålsbeskrivelse",
  sensitivity: "Type personopplysning",
  processingActivities: "Behandlingsaktiviteter",
  process: "Behandling",
  processes: "Behandlinger",
  legalBasis: "Rettslig grunnlag for behandlingen",
  legalBasisShort: "Rettslig grunnlag",
  legalBasesShort: "Rettslig grunnlag",
  subjectCategories: "Kategorier av personer",
  nationalLaw: "Nasjonal lov",
  navMaster: "Master i NAV",
  productTeam: "Produktteam",
  disclosure: "Utlevering",
  disclosures: "Utleveringer",
  documents: "Dokumenter",
  thirdParty: "Ekstern part",
  policy: 'Polis',
  usage: 'Bruk',
  and: 'og',
  remove: 'Fjern',
  yes: 'Ja',
  no: 'Nei',
  unclarified: 'Uavklart',
  automaticProcessing: 'Helautomatisert behandling',
  automaticProcessingExtra: 'Treffes det et vedtak eller en avgjørelse som er basert på helautomatisert behandling av personopplysninger? Altså avgjørelser uten menneskelig innvirkning.',
  profiling: 'Profilering',
  profilingExtra: 'Med profilering mener vi at personopplysninger behandles automatisk for å kunne analysere eller forutsi noe om preferanser, evner eller behov til en enkeltperson. analysering av personopplysninger for å kunne forutsi noe om en enkeltperson, f.eks. personens preferanser, evner eller behov.',
  dataProcessor: 'Databehandler',
  dataProcessorExtra: 'Brukes det databehandler for å utføre behandlingen/behandle personopplysninger?',
  dataProcessorAgreement: 'Saksnummer i Websak',
  dataProcessorOutsideEU: 'Utenfor EU / EØS',
  dataProcessorOutsideEUExtra: 'Behandles personopplysningene utenfor EU/EØS av databehandler?',

  loggedInStatus: "Du er logget inn og kan",
  notLoggedInStatus: "Du er ikke logget inn men kan",
  couldntLoad: "Kunne ikke laste inn siden",
  couldntLoadTerm: "Kunne ikke finne term",
  couldntLoadTeam: "Kunne ikke finne team",
  informationTypeCreate: "Opprett opplysningstype",
  sensitivitySelect: "Velg type personopplysning",
  nameWrite: "Skriv inn navn",
  categoriesWrite: "Skriv inn og legg til kategorier",
  sourcesWrite: "Skriv inn og legg til kilder",
  keywordsWrite: "Legg til nøkkelord",
  navMasterSelect: "Velg master",
  purposeSelect: "Velg formål",
  purposeNotFound: "Fant ingen formål",
  purposeUse: "Brukes til formål",
  informationTypeExternalUse: "Utleveres til",
  policyEdit: "Rediger behandling for opplysningstype",
  policyNew: "Opprett behandling for opplysningstype",
  processEdit: "Rediger behandling for opplysningstype",
  processingActivitiesNew: "Opprett ny behandling",
  processingActivitiesEdit: "Rediger behandling",
  processNew: "Legg til ny behandling",
  legalBasisNotFound: "Fant ingen rettslige grunnlag",
  legalBasisNew: "Nytt rettslig grunnlag",
  legalBasisAdd: "Legg til nytt rettslig grunnlag",
  gdprSelect: "Velg GDPR artikkel",
  nationalLawSelect: "Velg nasjonal lov",
  descriptionWrite: "Skriv inn beskrivelse",
  descriptionWriteLegalBasesF: "Spesifiser interessen",
  descriptionWriteLegalBasesCE: "Legg inn lovreferanse",
  definitionWrite: "Skriv inn en definisjon",
  subjectCategoriesNotFound: "Fant ingen kategorier av personer",
  legalBasesProcess: "Bruker behandlingens rettslige grunnlag",
  legalBasesUndecided: "Uavklart",
  legalBasesOwn: "Har eget rettslig grunnlag",
  legalBasesUndecidedWarning: "Rettslig grunnlag er ikke avklart",
  notAllowedMessage: "Du har ikke tilgang til denne siden.",
  confirmDeleteHeader: "Bekreft sletting",
  confirmDeletePolicyText: "Bekreft sletting av behandling for opplysningstypen",
  confirmDeleteProcessText: "Bekreft sletting av behandlingen ",
  cannotDeleteProcess: "Kan ikke slette behandlingen {0}, den inneholder fortsatt {1} opplysningstyp(er)",
  confirmDeleteInformationTypeText: "Bekreft sletting av opplysningstypen ",
  cannotDeleteInformationTypes: "Kan ikke slette opplysningstypen {0} da den er",
  informationTypeHasPolicies: " knyttet til {0} behandling(er)",
  informationTypeHasDocuments: " knyttet til {0} dokument(er)",
  startIllustration: "Illustrasjon av en prosess",
  treasureIllustration: "Illustration av en skatt",
  legalbasisGDPRArt9Info:
    "Opplysningstyper som er særlige kategorier krever art. 9",
  legalBasisInfo:
    "For artikkel 6(c, e og f) trengs det videre spesifisering.",
  disclosureSelect: "Velg mottaker",
  createThirdPartyModalTitle: 'Opprett utlevering for ekstern part',
  disclosuresToThirdParty: 'Utleveringer til ekstern part',
  retrievedFromThirdParty: 'Innhentinger fra ekstern part',
  usageNotFound: 'Fant ingen bruk',
  newValue: "Ny verdi",
  replace: "Erstatt",
  replaceAllUse: "Erstatt all bruk",
  recipientPurpose: "Mottakers formål",
  legalBasisComplete: "Lukk rettslig grunnlag redigering før lagring",
  validityOfProcess: "Gyldighetsperiode for behandlingen",
  validityOfPolicy: "Gyldighetsperiode for bruk av opplysningstypen i denne behandlingen",
  chooseDocument: "Velg et dokument for å starte",
  addDocument: "Legg til opplysningstyper fra dokument",
  searchDocuments: "Søk dokumenter",
  addOneInformationType: "Legg til én opplysningstype",
  addCollectionOfInformationTypes: "Legg til en samling av opplysningstyper",
  groupByPurpose: "Grupper etter formål",
  showAll: "Vis alle",
  emptyTable: "Ingen",
  pageNotFound: "Oida 404! Fant ikke den siden der nei",

  POLLY_READ: "Les",
  POLLY_WRITE: "Skriv",
  POLLY_ADMIN: "Admin",

  CREATE: "Opprett",
  UPDATE: "Oppdater",
  DELETE: "Slett",

  department: "Avdeling",
  subDepartment: "Linja (Ytre etat)",
  save: "Lagre",
  update: "Oppdater",
  abort: "Avbryt",
  login: "Logg inn",
  logout: "Logg ut",
  hi: "Hei",
  addNew: "Legg til ny",
  createNew: "Opprett ny",
  name: "Navn",
  email: "Email",
  copied: "Kopiert",
  groups: "Grupper",
  description: "Beskrivelse",
  document: "Dokument",
  edit: "Rediger",
  sources: "Kilder",
  categories: "Kategorier",
  keywords: "Nøkkelord",
  read: "Lese",
  write: "Skrive",
  administrate: "Admin",
  delete: "Slett",
  appName: "Behandlingskatalog",
  beta: "beta",
  all: "Alle",
  startDate: "Fom dato",
  endDate: "Tom dato",
  inactive: "Inaktiv",
  active: "Aktiv",
  preview: "Forhåndsvisning",
  view: "Vis",
  info: "Informasjon",
  ghost: "Vis bruk",
  version: "Versjonering",
  period: "Periode",
  recipient: "Mottaker",
  slack: "Slack kanal",
  add: "Legg til",

  prevButton: "Forrige",
  nextButton: "Neste",
  rows: "Rader",

  maxChars: "Maks {0} tegn",
  required: "Feltet er påkrevd",
  datePickStart: "Velg fra og med dato",
  datePickEnd: "Velg til og med dato",
  dateFormat: "Feil dato format, eksempel: 2018-08-22",
  useDates: "Velg datoer",

  requiredGdprArt6:
    "Opplysningstypen krever et rettslig grunnlag med artikkel 6",
  requiredGdprArt9:
    "Opplysningstypen krever et rettslig grunnlag med artikkel 9",
  requiredNationalLaw: "Artikkelen krever nasjonal lov",
  requiredDescription: "Artikkelen krever ytterligere beskrivelse",

  code: "Kode",
  codes: "Koder",
  shortName: "Kortnavn",
  createCodeListTitle: "Ny kode",
  deleteCodeListConfirmationTitle: "Bekreft sletting",
  editCodeListTitle: "Rediger kode",
  manageCodeListTitle: "Administrering av kodeverk",
  chooseCodeList: "Velg kodeverk",
  createNewCodeList: "Opprett ny kode",

  id: "Id",
  searchId: "Søk etter id",
  audit: "Versjonering",
  audits: "Versjoneringer",
  auditNr: "Versjon #",
  auditNotFound: "Fant ingen versjonering",
  table: "Tabellnavn",
  action: "Aksjon",
  time: "Tidspunkt",
  user: "Bruker",
  close: "Lukk",
  lastChanges: "Siste endringer",
  settings: "Instillinger",
  defaultProcessDocument: "Dokument for standard informasjonstyper i behandling"
}

export const en: IStrings = {
  informationType: "Information type",
  informationTypes: "Information types",
  informationTypeSearch: "Information type search",
  term: "Term definition",
  purpose: "Purpose",
  processPurpose: "Process purpose",
  purposeDescription: "General purpose description",
  sensitivity: "Type of personal data",
  processingActivities: "Processing activities",
  process: "Process",
  processes: "Processes",
  navMaster: "Master in NAV",
  legalBasis: "Legal basis for process",
  legalBasisShort: "Legal basis",
  legalBasesShort: "Legal bases",
  nationalLaw: "National law",
  subjectCategories: "Subject Categories",
  productTeam: "Product Team",
  disclosure: "Disclosure",
  disclosures: "Disclosures",
  documents: "Documents",
  thirdParty: 'Third party',
  policy: 'Policy',
  usage: 'Usage',
  and: 'and',
  remove: 'Remove',
  yes: 'Yes',
  no: 'No',
  unclarified: 'Unclarified',
  automaticProcessing: 'Automatic Processing',
  automaticProcessingExtra: 'Is a decision made based on fully automated processing of personal data? In other words, decisions that are made without human involvement.',
  profiling: 'Profiling',
  profilingExtra: 'By profiling we mean that personal data is processed automatically in order to analyze or predict something about the preferences, abilities or needs of an individual. Analyzing personal data is done to predict something about an individual, e.g. the person\'s preferences, abilities or needs.',
  dataProcessor: 'Data processor',
  dataProcessorExtra: 'Is a data processor used to perform the processing of personal data?',
  dataProcessorAgreement: 'Case number in Websak',
  dataProcessorOutsideEU: 'Outside EU / EEA',
  dataProcessorOutsideEUExtra: 'Is personal data processed outside EU/EEA by a data processor?',

  loggedInStatus: "You are logged in and can",
  notLoggedInStatus: "You are not logged in but you can still",
  couldntLoad: "Couldn't load the page",
  couldntLoadTerm: "Couldn't load the term",
  couldntLoadTeam: "Couldn't load the team",
  informationTypeCreate: "Create new information type",
  sensitivitySelect: "Select type of personal data",
  nameWrite: "Enter name",
  categoriesWrite: "Enter and add categories",
  sourcesWrite: "Enter and add sources",
  keywordsWrite: "Enter and add keywords",
  navMasterSelect: "Select master",
  purposeSelect: "Select purpose",
  purposeNotFound: "Found no purposes",
  purposeUse: "Used for purposes",
  informationTypeExternalUse: "External use",
  policyEdit: "Edit purpose for information type",
  policyNew: "Create new process for information type",
  processNew: "Add new process",
  legalBasisNotFound: "Found no legal bases",
  processEdit: "Edit process for information type",
  processingActivitiesNew: "Create new processing activity",
  processingActivitiesEdit: "Edit processing activity",
  legalBasisNew: "New legal basis",
  legalBasisAdd: "Add new legal basis",
  gdprSelect: "Select GDPR article",
  nationalLawSelect: "Select national law",
  descriptionWrite: "Enter description",
  descriptionWriteLegalBasesF: "Specify the interest",
  descriptionWriteLegalBasesCE: "Enter law reference",
  definitionWrite: "Enter definition",
  subjectCategoriesNotFound: "Found no subject categories",
  legalBasesProcess: "Use legal bases from process",
  legalBasesUndecided: "Undecided",
  legalBasesOwn: "Use explicit legal bases",
  legalBasesUndecidedWarning: "Legal bases missing",
  notAllowedMessage: "You don't have access to this page",
  confirmDeleteHeader: "Confirm delete",
  confirmDeletePolicyText: "Please confirm deleting the policy for",
  confirmDeleteProcessText: "Please confirm deleting the process ",
  cannotDeleteProcess: "Can't delete the process {0} as it contains {1} information type(s)",
  confirmDeleteInformationTypeText: "Please confirm deleting the of information type ",
  cannotDeleteInformationTypes: "Can't delete the information type {0} as it is",
  informationTypeHasPolicies: " connected to {0} process(es)",
  informationTypeHasDocuments: " connected to {0} document(s)",
  startIllustration: "Process illustration",
  treasureIllustration: "Treasure illustration",
  legalbasisGDPRArt9Info:
    "Informationtypes that are special categories require art. 9",
  legalBasisInfo:
    "For Article 6(c, e and f), further specification is needed.",
  disclosureSelect: "Select recipient",
  groupByPurpose: "Group by purpose",
  showAll: "Show all",
  createThirdPartyModalTitle: 'Create disclosure for a thirdparty',
  disclosuresToThirdParty: "Disclosures to",
  retrievedFromThirdParty: "Retrieved from thirdparties",
  usageNotFound: 'No usage found',
  newValue: "New Value",
  replace: "Replace",
  replaceAllUse: "Replace all use",
  recipientPurpose: "Recipient's purpose",
  legalBasisComplete: "Close legal basis editor before saving",
  validityOfProcess: "Validity of process",
  validityOfPolicy: "Validity of policy",
  chooseDocument: "Select document a document to start",
  addDocument: "Add information types from dokument",
  searchDocuments: "Search documents",
  addOneInformationType: "Add one information type",
  addCollectionOfInformationTypes: "Add a collection of information types",
  emptyTable: "No",
  pageNotFound: "Oops 404! Couldn't find that page",

  POLLY_READ: "Read",
  POLLY_WRITE: "Write",
  POLLY_ADMIN: "Admin",

  CREATE: "Create",
  UPDATE: "Update",
  DELETE: "Delete",

  department: "Department",
  subDepartment: "Sub department",
  save: "Save",
  update: "Update",
  abort: "Cancel",
  login: "Login",
  logout: "Logout",
  hi: "Hi",
  addNew: "Add new",
  createNew: "Create new",
  name: "Name",
  email: "Email",
  copied: "Copied",
  groups: "Groups",
  description: "Description",
  document: "Document",
  edit: "Edit",
  sources: "Sources",
  categories: "Categories",
  keywords: "Keywords",
  read: "Read",
  write: "Write",
  administrate: "Admin",
  delete: "Delete",
  appName: "Process catalog",
  beta: "beta",
  all: "All",
  startDate: "Start date",
  endDate: "End date",
  inactive: "Inactive",
  active: "Active",
  recipient: "Recipient",
  slack: "Slack channel",
  preview: "Preview",
  view: "View",
  ghost: "Usage",
  info: "Info",
  period: "Period",
  useDates: "Use dates",
  version: "Version",
  add: "Add",

  prevButton: "Prev",
  nextButton: "Next",
  rows: "Rows",

  maxChars: "Max {0} characters",
  required: "Field is required",
  dateFormat: "Incorrect date format, ex: 2018-08-22",
  datePickEnd: "Select to date (inclsuive)",
  datePickStart: "Select from date (inclusive)",

  requiredGdprArt6:
    "The information type requires a legal basis for article 6",
  requiredGdprArt9:
    "The information type requires a legal basis for article 9",
  requiredNationalLaw: "The article requires national law",
  requiredDescription: "The article requires additional description",


  code: "Code",
  codes: "Codes",
  shortName: "Short name",
  createCodeListTitle: "Create code",
  deleteCodeListConfirmationTitle: "Confirm deletion",
  editCodeListTitle: "Edit code",
  manageCodeListTitle: "Manage code lists",
  chooseCodeList: "Choose code list",
  createNewCodeList: "Create new code",

  id: "Id",
  searchId: "Search for id",
  audit: "Audit",
  audits: "Audits",
  auditNr: "Audit #",
  auditNotFound: "No audits found",
  table: "Table name",
  action: "Action",
  time: "Time",
  user: "User",
  close: "Close",
  lastChanges: "Last changes",
  settings: "Settings",
  defaultProcessDocument: "Document for the default information types in a process"
};

export const ta = {
  POLLY_ADMIN: "நிர்வாகம்",
  POLLY_READ: "படிக்க",
  POLLY_WRITE: "எழுது",
  all: "அனைத்து",
  appName: "செயல்முறை பட்டியல்",
  beta: "பீட்டா",
  confirmDeletePolicyHeader: "நீக்கு என்பதை உறுதிப்படுத்தவும்",
  confirmDeletePolicyText: "இதற்கான கொள்கையை நீக்குவதை உறுதிப்படுத்தவும்",
  delete: "அழி",
  email: "மின்னஞ்சல்",
  endDate: "கடைசி தேதி",
  groups: "குழுக்கள்",
  inactive: "செயல்படா",
  maxChars: "அதிகபட்ச {0} எழுத்துக்கள்",
  nextButton: "அடுத்த",
  notAllowedMessage: "",
  prevButton: "முந்தைய",
  processes: "செயல்முறைகள்",
  required: "தேவையான",
  rows: "வரிசைகள்",
  startDate: "தொடக்க தேதி",

  informationType: "தகவல் வகை",
  informationTypes: "தகவல் வகைகள்",
  informationTypeSearch: "தகவல் வகை தேடல்",
  term: "கால வரையறை",
  purpose: "நோக்கம்",
  sensitivity: "உணர்திறன்",
  processingActivities: "செயலாக்க செயல்பாடு",
  process: "செயல்முறை",
  navMaster: "மாஸ்டர் NAV",
  legalBasis: "செயல்முறைக்கு சட்டபூர்வமான அடிப்படை",
  legalBasisShort: "சட்ட அடிப்படையில்",
  legalBasesShort: "சட்ட தளங்கள்",
  nationalLaw: "தேசிய சட்டம்",
  subjectCategories: "பொருள் வகைகள்",

  loggedInStatus: "நீங்கள் உள்நுழைந்துள்ளீர்கள், முடியும்",
  notLoggedInStatus:
    "நீங்கள் உள்நுழைந்திருக்கவில்லை, ஆனால் நீங்கள் இன்னும் முடியும்",
  couldntLoad: "பக்கத்தை ஏற்ற முடியவில்லை",
  informationTypeCreate: "புதிய தகவல் வகையை உருவாக்கு",
  sensitivitySelect: "தனிப்பட்ட தரவின் வகையைத் தேர்ந்தெடுக்கவும்",
  nameWrite: "பெயரை உள்ளிடுக",
  categoriesWrite: "வகைகளை உள்ளிட்டு சேர்க்கவும்",
  sourcesWrite: "மூலங்களை உள்ளிட்டு சேர்க்கவும்",
  keywordsWrite: "முக்கிய வார்த்தைகளை உள்ளிட்டு சேர்க்கவும்",
  navMasterSelect: "மாஸ்டரைத் தேர்ந்தெடு",
  purposeSelect: "நோக்கத்தைத் தேர்ந்தெடு",
  purposeNotFound: "எந்த நோக்கங்களும் இல்லை",
  purposeUse: "நோக்கங்களுக்காகப் பயன்படுத்தப்படுகிறது",
  policyEdit: "தகவல் வகைக்கான நோக்கத்தைத் திருத்து",
  policyNew: "தகவல் வகைக்கு புதிய செயல்முறையை உருவாக்கு",
  processNew: "புதிய செயல்முறையைச் சேர்",
  legalBasisNotFound: "சட்ட தளங்கள் எதுவும் இல்லை",
  processEdit: "தகவல் வகைக்கான செயல்முறையைத் திருத்து",
  processingActivitiesNew: "புதிய செயலாக்க செயல்பாட்டை உருவாக்கு",
  processingActivitiesEdit: "செயலாக்க செயல்பாட்டைத் திருத்து",
  legalBasisNew: "புதிய சட்ட அடிப்படை",
  legalBasisAdd: "புதிய சட்ட அடிப்படையைச் சேர்",
  gdprSelect: "ஜிடிபிஆர் கட்டுரையைத் தேர்ந்தெடுக்கவும்",
  nationalLawSelect: "தேசிய சட்டத்தைத் தேர்ந்தெடு",
  descriptionWrite: "விளக்கத்தை உள்ளிடுக",
  definitionWrite: "வரையறையை உள்ளிடுக",
  subjectCategoriesNotFound: "பொருள் வகைகள் எதுவும் இல்லை",
  legalBasesProcess: "செயல்முறையிலிருந்து சட்ட தளங்களைப் பயன்படுத்துங்கள்",
  legalBasesUndecided: "தீர்மானிக்கப்படாதது",
  legalBasesOwn: "வெளிப்படையான சட்ட தளங்களைப் பயன்படுத்துங்கள்",
  legalBasesUndecidedWarning: "சட்ட தளங்கள் இல்லை",

  department: "துறை",
  subDepartment: "துணைத் துறை",
  save: "சேமி",
  abort: "ரத்துசெய்",
  login: "உள்நுழை",
  logout: "வெளியேறு",
  hi: "ஹாய்",
  addNew: "புதியதைச் சேர்",
  createNew: "புதியதை உருவாக்கு",
  name: "பெயர்",
  description: "விளக்கம்",
  edit: "திருத்து",
  sources: "ஆதாரங்கள்",
  categories: "வகைகள்",
  keywords: "சொற்கள்",
  read: "படிக்க",
  write: "எழுது",
  administrate: "நிர்வாகி"
};
