name: Build and deploy PROD

on:
  push:
    branches:
      - prod

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/prod:${{ github.sha }}

jobs:
  build:
    name: Build and push docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Build
        run: |
          cp .env.prod .env
          yarn
          CI=false yarn run build
      - name: Docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-prod:
    name: Deploy to NAIS Prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais.yaml
          VARS: prod.yaml
