version: 2.1
orbs:
  nais: navikt/nais-deployment@3.2.0
jobs:
  build:
    machine:
      enabled: true
    environment:
      JAVA_HOME: /tmp/java
    steps:
      - checkout
      - restore_cache:
          name: Restore java cache
          key: java-{{ checksum ".circleci/install_java.sh" }}
      - run:
          name: Install java
          command: cat ${JAVA_HOME}/release || bash .circleci/install_java.sh
      - restore_cache:
          name: Restore m2 cache
          key: m2-{{ checksum "pom.xml" }}
      - run:
          name: Build application
          command: |
            mvn --version
            mvn package
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/.*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - persist_to_workspace:
         root: .
         paths:
           - polly-app/target/app-exec.jar
           - Dockerfile
      - save_cache:
          name: Cache m2
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - save_cache:
          name: Cache Java
          key: java-{{ checksum ".circleci/install_java.sh" }}
          paths:
            - /tmp/java
  build_docker_image:
    docker:
        - image: circleci/openjdk:stretch
    steps:
      - attach_workspace:
          at: ~/project
      - nais/docker:
          image: navikt/polly
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - build_docker_image:
          context: NAIS deployment
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - prod
      - nais/deploy-gh-app:
          name: Deploy preprod
          context: NAIS deployment
          build-and-push-docker-image: false
          repo: navikt/polly
          image: navikt/polly
          github-app-id: 26100
          nais-template: naiserator-preprod.yaml
          environment: dev-fss
          team: teamdatajegerne
          requires:
            - build_docker_image
          filters:
            branches:
              only:
                - master
      - nais/deploy-gh-app:
          name: Deploy prod
          context: NAIS deployment
          build-and-push-docker-image: false
          repo: navikt/polly
          image: navikt/polly
          github-app-id: 26100
          nais-template: naiserator-prod.yaml
          environment: prod-fss
          team: teamdatajegerne
          requires:
            - build_docker_image
          filters:
            branches:
              only:
                - prod
