version: 2.1
orbs:
  nais: navikt/nais-deployment@1.1.1
jobs:
  build:
    working_directory: ~/backend_wf
    docker:
      - image: circleci/openjdk:11.0.3-stretch
    steps:
      - checkout
      - restore_cache:
          key: backend_wf-{{ checksum "pom.xml" }}
      - run:
          name: Build application
          command: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: backend_wf-{{ checksum "pom.xml" }}
      - nais/docker-deploy:
          image: navikt/data-catalog-backend
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          context: NAIS deployment
      - nais/deploy-preprod:
          context: NAIS deployment
          build-and-push-docker-image: false
          repo: navikt/data-catalog-backend
          image: navikt/data-catalog-backend
          github-app-id: 26100
          nais-template: naiserator-preprod.yaml
          environment: dev-sbs
          team: teamdatajegerne
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - nais/deploy-prod:
          context: NAIS deployment
          build-and-push-docker-image: false
          repo: navikt/data-catalog-backend
          image: navikt/data-catalog-backend
          github-app-id: 26100
          nais-template: naiserator-prod.yaml
          environment: dev-sbs
          team: teamdatajegerne
          requires:
            - build
          filters:
            branches:
              only:
                - prod