version: 2.1
orbs:
  gcp-gke: circleci/gcp-gke@0.2.0
  gcp-gcr: circleci/gcp-gcr@0.6.1
jobs:
  build:
    working_directory: ~/backend_wf
    docker:
      - image: circleci/openjdk:11.0.3-stretch
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build application
        command: mvn clean install
    - run:
        name: Generate version number and docker image tags and copy jars
        command: |
          mkdir /tmp/workspace
          export RELEASE_VERSION=$CIRCLE_BUILD_NUM
          echo "export RELEASE_VERSION=$RELEASE_VERSION" >> /tmp/workspace/properties.env
          echo "export DOCKER_TAG=\"$CIRCLE_PROJECT_REPONAME:$RELEASE_VERSION\"" >> /tmp/workspace/properties.env
          cp ./data-catalog-backend-app/target/app-exec.jar /tmp/workspace/app-exec.jar
    - persist_to_workspace:
        root: /tmp/workspace
        paths:
          - app-exec.jar
          - properties.env
  deploy_to_staging:
    environment:
      - PROJECT_NAME: "datajegerne"
      - GOOGLE_PROJECT_ID: "datajegerne"
      - GOOGLE_COMPUTE_ZONE: "europe-north1-b"
      - GOOGLE_CLUSTER_NAME: "datajegerne-cluster"
    working_directory: ~/backend_wf
    docker:
      - image: circleci/openjdk:11.0.3-stretch
    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: /tmp/workspace
    - run:
        name: Copy jar and env
        command: |
          mkdir ./data-catalog-backend-app/target/
          cp /tmp/workspace/app-exec.jar ./data-catalog-backend-app/target/app-exec.jar
          cat /tmp/workspace/properties.env >> $BASH_ENV
    - run:
        name: apt update
        command: sudo apt-get update || sudo apt-get update
    - gcp-gcr/gcr-auth
    - gcp-gcr/build-image:
        image: navikt/data-catalog-backend
        tag: $RELEASE_VERSION
    - gcp-gcr/push-image:
        image: navikt/data-catalog-backend
        tag: $RELEASE_VERSION
    - gcp-gke/install
    - gcp-gke/init
# Timeout pga at clusteret er privat.
#    - gcp-gke/rollout-image:
#        cluster: datajegerne-cluster
#        deployment: data-catalog-backend
#        container: data-catalog-backend
#        image: gcr.io/datajegerne/navikt/$CIRCLE_PROJECT_REPONAME:$RELEASE_VERSION
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          context: datajegerne
      - deploy_to_staging:
          requires:
            - build
          filters:
            branches:
              only: master
          context: datajegerne