version: 2.1
orbs:
  nais: navikt/nais-deployment@1.1.1
jobs:
  build:
    machine:
      enabled: true
    environment:
      JAVA_HOME: /tmp/java
    steps:
      - checkout
      - restore_cache:
          key: java11-{{ checksum ".circleci/install_java.sh" }}
      - run:
          name: Install java11
          command: cat ${JAVA_HOME}/release || bash .circleci/install_java.sh
      - restore_cache:
          key: m2-{{ checksum "pom.xml" }}
      - run:
          name: Build application
          command: |
            mvn --version
            mvn package
      - persist_to_workspace:
         root: .
         paths:
           - data-catalog-backend-app/target/app-exec.jar
           - Dockerfile
      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - save_cache:
          key: java11-{{ checksum ".circleci/install_java.sh" }}
          paths:
            - /tmp/java
  build_docker_image:
    docker:
        - image: circleci/openjdk:11-stretch
    steps:
      - attach_workspace:
          at: ~/project
      - nais/docker-deploy:
          image: navikt/data-catalog-backend
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - build_docker_image:
          context: NAIS deployment
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - prod
      - nais/deploy:
          name: Deploy preprod
          context: NAIS deployment
          build-and-push-docker-image: false
          repo: navikt/data-catalog-backend
          image: navikt/data-catalog-backend
          github-app-id: 26100
          nais-template: naiserator-preprod.yaml
          environment: dev-sbs
          team: teamdatajegerne
          requires:
            - build_docker_image
          filters:
            branches:
              only:
                - master
      - nais/deploy:
          name: Deploy prod
          context: NAIS deployment
          build-and-push-docker-image: false
          repo: navikt/data-catalog-backend
          image: navikt/data-catalog-backend
          github-app-id: 26100
          nais-template: naiserator-prod.yaml
          environment: prod-sbs
          team: teamdatajegerne
          requires:
            - build_docker_image
          filters:
            branches:
              only:
                - prod