CREATE TABLE IF NOT EXISTS DISCLOSURE
(
    DISCLOSURE_ID      UUID PRIMARY KEY,
    DATA               JSONB     NOT NULL,
    CREATED_BY         TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY   TEXT,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DISCLOSURE_INFORMATION_TYPE
(
    DISCLOSURE_ID       UUID NOT NULL REFERENCES DISCLOSURE,
    INFORMATION_TYPE_ID UUID NOT NULL REFERENCES INFORMATION_TYPE,
    CONSTRAINT DISCLOSURE_INFTYPE_PKEY PRIMARY KEY (DISCLOSURE_ID, INFORMATION_TYPE_ID)
);
