ALTER TABLE AUDIT_VERSION
    DROP COLUMN TIME,
    ADD COLUMN TIME TIMESTAMP;

UPDATE AUDIT_VERSION
SET TIME = NOW()
WHERE TIME IS NULL;

ALTER TABLE AUDIT_VERSION
    ALTER COLUMN TIME SET NOT NULL;