CREATE TABLE IF NOT EXISTS AUDIT_VERSION
(
    AUDIT_ID   UUID PRIMARY KEY,
    ACTION     TEXT  NOT NULL,
    TABLE_NAME TEXT  NOT NULL,
    TABLE_ID   TEXT  NOT NULL,
    TIME       DATE  NOT NULL,
    DATA       JSONB NOT NULL
);
