-- Ekte optimistisk låsing (jakarta.persistence.Version).
-- Alle entiteter som arver Auditable (@MappedSuperclass).
-- AUDIT_VERSION er ren historikk/append-only og trenger ikke optimistisk låsing.
-- AUTH er serverside sesjonsbokføring som skrives på nesten hvert kall (LAST_ACTIVE) og er
-- bevisst holdt utenfor - se kommentar i Auth.java.

ALTER TABLE PROCESS ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 0;
ALTER TABLE DP_PROCESS ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 0;
ALTER TABLE POLICY ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 0;
ALTER TABLE INFORMATION_TYPE ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 0;
ALTER TABLE CODELIST ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 0;
ALTER TABLE DOCUMENT ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 0;
ALTER TABLE DISCLOSURE ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 0;
ALTER TABLE PROCESSOR ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 0;
ALTER TABLE GENERIC_STORAGE ADD COLUMN VERSION INTEGER NOT NULL DEFAULT 0;
