ALTER TABLE POLICY
    ADD COLUMN LEGAL_BASES_INHERITED BOOLEAN;

UPDATE POLICY
SET LEGAL_BASES_INHERITED = FALSE
WHERE LEGAL_BASES_INHERITED IS NULL;

ALTER TABLE POLICY
    ALTER COLUMN LEGAL_BASES_INHERITED SET NOT NULL;