ALTER TABLE INFORMATION_TYPE
    DROP CONSTRAINT IF EXISTS INFORMATION_TYPE_CONTEXT;

ALTER TABLE PROCESS
    ADD COLUMN START_DATE DATE,
    ADD COLUMN END_DATE   DATE;

UPDATE PROCESS
SET START_DATE = '0001-01-01'
WHERE START_DATE IS NULL;
UPDATE PROCESS
SET END_DATE = '9999-12-31'
WHERE END_DATE IS NULL;

ALTER TABLE PROCESS
    ALTER COLUMN START_DATE SET NOT NULL,
    ALTER COLUMN END_DATE SET NOT NULL;
