ALTER TABLE DATASET
    DROP COLUMN ELASTICSEARCH_ID;

ALTER TABLE POL_DATASETT
    DROP COLUMN CREATED_BY,
    DROP COLUMN LAST_MODIFIED_BY,
    DROP COLUMN CREATED_DATE,
    DROP COLUMN LAST_MODIFIED_DATE;
