CREATE SEQUENCE IF NOT EXISTS SEQ_POLICY;

CREATE TABLE IF NOT EXISTS POLICY (
    POLICY_ID INTEGER DEFAULT NEXTVAL('SEQ_POLICY') PRIMARY KEY,
    INFORMATION_TYPE_ID INTEGER NOT NULL,
    PURPOSE_CODE VARCHAR(100) NOT NULL,
    LEGAL_BASIS_DESCRIPTION TEXT,
    CREATED_BY VARCHAR(200) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY VARCHAR(200),
    LAST_MODIFIED_DATE TIMESTAMP,
    UNIQUE (INFORMATION_TYPE_ID, PURPOSE_CODE));
