ALTER TABLE POLICY
    ADD COLUMN FOM DATE,
    ADD COLUMN TOM DATE;

UPDATE POLICY
SET FOM = DATE '0001-1-1'
WHERE FOM IS NULL;

UPDATE POLICY
SET TOM = DATE '9999-1-1'
WHERE TOM IS NULL;

ALTER TABLE POLICY
    ALTER COLUMN FOM SET NOT NULL,
    ALTER COLUMN TOM SET NOT NULL;