CREATE TABLE IF NOT EXISTS CODELIST
(
    LIST_NAME          TEXT      NOT NULL,
    CODE               TEXT      NOT NULL,
    NORMALIZED_CODE    TEXT      NOT NULL,
    DESCRIPTION        TEXT      NOT NULL,
    CREATED_BY         TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY   TEXT,
    LAST_MODIFIED_DATE TIMESTAMP,
    UNIQUE (LIST_NAME, CODE)
);

CREATE TABLE IF NOT EXISTS TERM
(
    TERM_ID            UUID PRIMARY KEY,
    NAME               TEXT      NOT NULL,
    DESCRIPTION        TEXT      NOT NULL,
    CREATED_BY         TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY   TEXT,
    LAST_MODIFIED_DATE TIMESTAMP,
    UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS PROCESS
(
    PROCESS_ID         UUID PRIMARY KEY,
    NAME               TEXT      NOT NULL,
    CREATED_BY         TEXT      NOT NULL,
    CREATED_DATE       TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY   TEXT,
    LAST_MODIFIED_DATE TIMESTAMP,
    UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS INFORMATION_TYPE
(
    INFORMATION_TYPE_ID  UUID PRIMARY KEY,
    TERM_ID              UUID REFERENCES TERM,
    ELASTICSEARCH_STATUS TEXT      NOT NULL,
    DATA                 JSONB     NOT NULL,
    CREATED_BY           TEXT      NOT NULL,
    CREATED_DATE         TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY     TEXT,
    LAST_MODIFIED_DATE   TIMESTAMP
);

CREATE TABLE IF NOT EXISTS POLICY
(
    POLICY_ID             UUID PRIMARY KEY,
    INFORMATION_TYPE_ID   UUID      NOT NULL REFERENCES INFORMATION_TYPE,
    PROCESS_ID            UUID REFERENCES PROCESS,
    INFORMATION_TYPE_NAME TEXT      NOT NULL,
    PURPOSE_CODE          TEXT      NOT NULL,
    SUBJECT_CATEGORIES    TEXT      NOT NULL,
    LEGAL_BASES           JSONB     NOT NULL,
    START_DATE            DATE      NOT NULL,
    END_DATE              DATE      NOT NULL,
    CREATED_BY            TEXT      NOT NULL,
    CREATED_DATE          TIMESTAMP NOT NULL,
    LAST_MODIFIED_BY      TEXT,
    LAST_MODIFIED_DATE    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GITHUB_STATUS
(
    GITHUB_STATUS_ID BIGSERIAL PRIMARY KEY,
    GITHUB_SHA      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BEHANDLINGSGRUNNLAG_DISTRIBUTION
(
    ID      UUID PRIMARY KEY,
    PURPOSE TEXT NOT NULL
);

ALTER TABLE INFORMATION_TYPE
    DROP CONSTRAINT IF EXISTS INFORMATION_TYPE_NAME;
ALTER TABLE INFORMATION_TYPE
    DROP CONSTRAINT IF EXISTS INFORMATION_TYPE_CONTEXT;

ALTER TABLE INFORMATION_TYPE
    ADD CONSTRAINT INFORMATION_TYPE_NAME CHECK (DATA ? 'name'::TEXT);
ALTER TABLE INFORMATION_TYPE
    ADD CONSTRAINT INFORMATION_TYPE_CONTEXT CHECK (DATA ? 'context'::TEXT);

CREATE INDEX IF NOT EXISTS INFORMATION_TYPE_IDX_NAME ON INFORMATION_TYPE ((DATA ->> 'name'::TEXT));