CREATE SCHEMA IF NOT EXISTS BACKEND_SCHEMA;

CREATE IF NOT EXISTS SEQUENCE BACKEND_SCHEMA.SEQ_INFORMATION_TYPE;

CREATE TABLE IF NOT EXISTS BACKEND_SCHEMA.CODELIST
(
  LIST_NAME           VARCHAR(100)   NOT NULL,
  CODE                VARCHAR(100)    NOT NULL,
  DESCRIPTION         TEXT    NOT NULL,
  PRIMARY KEY         (LIST_NAME, CODE)
);

CREATE TABLE IF NOT EXISTS BACKEND_SCHEMA.INFORMATION_TYPE
(
  INFORMATION_TYPE_ID     INTEGER DEFAULT nextval('BACKEND_SCHEMA.SEQ_INFORMATION_TYPE') PRIMARY KEY,
  NAME                    VARCHAR(100) UNIQUE NOT NULL,
  DESCRIPTION             TEXT        NOT NULL,
  CATEGORY                TEXT        NOT NULL,
  PRODUCER                TEXT        NOT NULL,
  SYSTEM                  TEXT        NOT NULL,
  CREATED_TIME            TIMESTAMP,
  CREATED_BY              TEXT,
  UPDATED_TIME            TIMESTAMP,
  UPDATED_BY              TEXT,
  PERSONAL_DATA           BOOLEAN     NOT NULL,
  ELASTICSEARCH_ID        TEXT,
  ELASTICSEARCH_STATUS    TEXT        NOT NULL
);
