-- Load data into BACKEND_SCHEMA.INFORMATION_PRODUCER
INSERT INTO BACKEND_SCHEMA.INFORMATION_PRODUCER (CODE, DECODE)
VALUES ('SKATTEETATEN', 'Skatteetaten');
INSERT INTO BACKEND_SCHEMA.INFORMATION_PRODUCER (CODE, DECODE)
VALUES('UTLENDINGSDIREKTORATET', 'Utlendingsdirektoratet');
INSERT INTO BACKEND_SCHEMA.INFORMATION_PRODUCER (CODE, DECODE)
VALUES ('UTENLANDS_TRYGDEMYNDIGHET', 'Utenlands trygdemyndighet');
INSERT INTO BACKEND_SCHEMA.INFORMATION_PRODUCER (CODE, DECODE)
VALUES('ARBEIDSGIVER', 'Arbeidsgiver');
INSERT INTO BACKEND_SCHEMA.INFORMATION_PRODUCER (CODE, DECODE)
VALUES('REVISOR', 'Revisor');

-- Load data into BACKEND_SCHEMA.INFORMATION_CATEGORY
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('PERSONALIA', 'Personalia');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('KONTAKTOPPLYSNINGER', 'Adresse og kontaktopplysninger');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('FAMILIERELASJONER', 'Familierelasjoner');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('FULLMEKTIG', 'Verge og fullmektig');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('FOLKETRYGD', 'Opphold og medlemskap i folketrygden');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('ARBEIDSFORHOLD', 'Arbeidsforhold');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('UTDANNING', 'Utdanning');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('CV', 'CV');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('SKOLE_BARNEHAGE', 'Opplysninger om skole og barnehageplass');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('INNTEKT_YTELSER', 'Inntekt, trygde- og pensjonsytelser');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('SKATTEOPPLYSNINGER', 'Skatteopplysninger');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('OKONOMISKE_OPPLYSNINGER', 'Andre økonomiske opplysninger');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('HELSEOPPLYSNNGER', 'Helseopplysninger');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('INSTITUSJONSOPPHOLD', 'Institusjonsopphold');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('LOVOVERTREDELSER', 'Straffedommer og lovovertredelser');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('BIOMETRISKE_KJENNETEGN', 'Biometriske kjennetegn som kan identifisere enkeltperson');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('MEDIER_KJENNETEGN', 'Personportrett, video- og lydopptak som kan identifisere enkeltperson');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('MOTORVOGNOPPLYSNINGER', 'Motorvognopplysninger');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('TRO_ETNISITET', 'Opplysninger om trossamfunn og etnisitet');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('VERNEPLIKT', 'Opplysninger om verneplikt');
INSERT INTO BACKEND_SCHEMA.INFORMATION_CATEGORY (CODE, DECODE)
VALUES ('REISEVEI', 'Opplysninger om reisevei');

-- Load data into BACKEND_SCHEMA.INFORMATION_SYSTEM
INSERT INTO BACKEND_SCHEMA.INFORMATION_SYSTEM (CODE, DECODE)
VALUES ('TPS', 'Tjenestebasert PersondataSystem');
INSERT INTO BACKEND_SCHEMA.INFORMATION_SYSTEM (CODE, DECODE)
VALUES ('INST', 'Institusjonsopphold');
INSERT INTO BACKEND_SCHEMA.INFORMATION_SYSTEM (CODE, DECODE)
VALUES ('POPP', 'Pensjonfaglig opptjeningsregiste');
INSERT INTO BACKEND_SCHEMA.INFORMATION_SYSTEM (CODE, DECODE)
VALUES ('TP', 'Tjenestepensjon');
INSERT INTO BACKEND_SCHEMA.INFORMATION_SYSTEM (CODE, DECODE)
VALUES ('AA_REG', 'Arbeidsgiver / Arbeidstaker register');
INSERT INTO BACKEND_SCHEMA.INFORMATION_SYSTEM (CODE, DECODE)
VALUES ('OPPDRAG', 'Oppdragssystemet');
INSERT INTO BACKEND_SCHEMA.INFORMATION_SYSTEM (CODE, DECODE)
VALUES ('PESYS', 'Pensjonssystem');
INSERT INTO BACKEND_SCHEMA.INFORMATION_SYSTEM (CODE, DECODE)
VALUES ('ARENA', 'Arbeidsrelatert saksbehandlingsystem');
INSERT INTO BACKEND_SCHEMA.INFORMATION_SYSTEM (CODE, DECODE)
VALUES ('INFOTRYGD', 'System for saksbehandling av ytelser og trygd');
INSERT INTO BACKEND_SCHEMA.INFORMATION_SYSTEM (CODE, DECODE)
VALUES ('BISYS', 'Bidragsløsningen');
