-- PRODUCER
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('PRODUCER', 'SKATTEETATEN', 'Skatteetaten');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('PRODUCER', 'BRUKER', 'Informasjon oppgitt av bruker');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('PRODUCER', 'UTLENDINGSDIREKTORATET', 'Utlendingsdirektoratet');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('PRODUCER', 'UTENLANDS_TRYGDEMYNDIGHET', 'Utenlands trygdemyndighet');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('PRODUCER', 'ARBEIDSGIVER', 'Arbeidsgiver');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('PRODUCER', 'REVISOR', 'Revisor');

-- CATEGORY
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'PERSONALIA', 'Personalia');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'KONTAKTOPPLYSNINGER', 'Adresse og kontaktopplysninger');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'FAMILIERELASJONER', 'Familierelasjoner');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'FULLMEKTIG', 'Verge og fullmektig');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'FOLKETRYGD', 'Opphold og medlemskap i folketrygden');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'ARBEIDSFORHOLD', 'Arbeidsforhold');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'UTDANNING', 'Utdanning');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'CV', 'CV');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'SKOLE_BARNEHAGE', 'Opplysninger om skole og barnehageplass');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'INNTEKT_YTELSER', 'Inntekt, trygde- og pensjonsytelser');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'SKATTEOPPLYSNINGER', 'Skatteopplysninger');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'OKONOMISKE_OPPLYSNINGER', 'Andre økonomiske opplysninger');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'HELSEOPPLYSNNGER', 'Helseopplysninger');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'INSTITUSJONSOPPHOLD', 'Institusjonsopphold');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'LOVOVERTREDELSER', 'Straffedommer og lovovertredelser');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'BIOMETRISKE_KJENNETEGN', 'Biometriske kjennetegn som kan identifisere enkeltperson');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'MEDIER_KJENNETEGN', 'Personportrett, video- og lydopptak som kan identifisere enkeltperson');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'MOTORVOGNOPPLYSNINGER', 'Motorvognopplysninger');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'TRO_ETNISITET', 'Opplysninger om trossamfunn og etnisitet');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'VERNEPLIKT', 'Opplysninger om verneplikt');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('CATEGORY', 'REISEVEI', 'Opplysninger om reisevei');

-- SYSTEM
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('SYSTEM', 'TPS', 'Tjenestebasert PersondataSystem');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('SYSTEM', 'INST', 'Institusjonsopphold');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('SYSTEM', 'POPP', 'Pensjonfaglig opptjeningsregiste');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('SYSTEM', 'TP', 'Tjenestepensjon');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('SYSTEM', 'AA_REG', 'Arbeidsgiver / Arbeidstaker register');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('SYSTEM', 'OPPDRAG', 'Oppdragssystemet');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('SYSTEM', 'PESYS', 'Pensjonssystem');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('SYSTEM', 'ARENA', 'Arbeidsrelatert saksbehandlingsystem');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('SYSTEM', 'INFOTRYGD', 'System for saksbehandling av ytelser og trygd');
INSERT INTO BACKEND_SCHEMA.CODELIST(LIST_NAME, CODE, DESCRIPTION)
VALUES ('SYSTEM', 'BISYS', 'Bidragsløsningen');

