-- InformationProducer
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationProducer', 'SKATTEETATEN', 'Skatteetaten');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationProducer', 'UTLENDINGSDIREKTORATET', 'Utlendingsdirektoratet');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationProducer', 'UTENLANDS_TRYGDEMYNDIGHET', 'Utenlands trygdemyndighet');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationProducer', 'ARBEIDSGIVER', 'Arbeidsgiver');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationProducer', 'REVISOR', 'Revisor');
-- InformationCategory
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'PERSONALIA', 'Personalia');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'KONTAKTOPPLYSNINGER', 'Adresse og kontaktopplysninger');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'FAMILIERELASJONER', 'Familierelasjoner');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'FULLMEKTIG', 'Verge og fullmektig');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'FOLKETRYGD', 'Opphold og medlemskap i folketrygden');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'ARBEIDSFORHOLD', 'Arbeidsforhold');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'UTDANNING', 'Utdanning');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'CV', 'CV');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'SKOLE_BARNEHAGE', 'Opplysninger om skole og barnehageplass');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'INNTEKT_YTELSER', 'Inntekt, trygde- og pensjonsytelser');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'SKATTEOPPLYSNINGER', 'Skatteopplysninger');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'OKONOMISKE_OPPLYSNINGER', 'Andre økonomiske opplysninger');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'HELSEOPPLYSNNGER', 'Helseopplysninger');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'INSTITUSJONSOPPHOLD', 'Institusjonsopphold');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'LOVOVERTREDELSER', 'Straffedommer og lovovertredelser');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'BIOMETRISKE_KJENNETEGN', 'Biometriske kjennetegn som kan identifisere enkeltperson');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'MEDIER_KJENNETEGN', 'Personportrett, video- og lydopptak som kan identifisere enkeltperson');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'MOTORVOGNOPPLYSNINGER', 'Motorvognopplysninger');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'TRO_ETNISITET', 'Opplysninger om trossamfunn og etnisitet');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'VERNEPLIKT', 'Opplysninger om verneplikt');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationCategory', 'REISEVEI', 'Opplysninger om reisevei');

-- InformationSystem
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationSystem', 'TPS', 'Tjenestebasert PersondataSystem');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationSystem', 'INST', 'Institusjonsopphold');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationSystem', 'POPP', 'Pensjonfaglig opptjeningsregiste');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationSystem', 'TP', 'Tjenestepensjon');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationSystem', 'AA_REG', 'Arbeidsgiver / Arbeidstaker register');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationSystem', 'OPPDRAG', 'Oppdragssystemet');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationSystem', 'PESYS', 'Pensjonssystem');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationSystem', 'ARENA', 'Arbeidsrelatert saksbehandlingsystem');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationSystem', 'INFOTRYGD', 'System for saksbehandling av ytelser og trygd');
INSERT INTO BACKEND_SCHEMA.LOOKUP_TABLE(ENTITY, CODE, DESCRIPTION)
VALUES ('InformationSystem', 'BISYS', 'Bidragsløsningen');

