ALTER TABLE DATASET
    ADD CONSTRAINT DATASET_JB_TITLE CHECK (JSON_PROPERTY ? 'title'::TEXT);

CREATE INDEX DATASET_IDX_TITLE ON DATASET ((JSON_PROPERTY ->> 'title'::TEXT));

DROP INDEX IF EXISTS UK_INFORMATION_TYPE;
DROP TABLE IF EXISTS INFORMATION_TYPE;

ALTER TABLE DISTRIBUTION_CHANNEL
    ADD COLUMN TYPE TEXT;

ALTER TABLE DISTRIBUTION_CHANNEL
    ALTER COLUMN description DROP NOT NULL;
