ALTER TABLE CODELIST
    ADD COLUMN NORMALIZED_CODE VARCHAR(100);

UPDATE CODELIST
SET NORMALIZED_CODE = regexp_replace(UPPER(CODE), '[^A-ZÆØÅ0-9]*', '')
WHERE NORMALIZED_CODE IS NULL;

ALTER TABLE CODELIST
    ALTER COLUMN NORMALIZED_CODE SET NOT NULL;
