name: Backend

on: 
  push:
    paths:
      - '.github/workflows/backend.yml'
      - 'apps/backend/**'

env:
  IMAGE: ghcr.io/${{ github.repository }}/behandlingskatalog-backend:${{ github.sha }}

defaults:
  run:
    working-directory: apps/backend

jobs:
  build:
    name: Backend - build and push docker
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17.x'

      - name: Build
        run: mvn compile

      - name: Test and Package
        run: mvn package

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{env.IMAGE}}
          context: ./apps/backend

  deploy-dev-GCP:
    name: Backend - deploy Dev GCP
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/backend/nais/behandlingskatalog-configmap-dev-gcp.yaml,apps/backend/nais/backend-gcp.yaml
          VARS: apps/backend/nais/backend-dev-gcp-vars.yaml
          ENVIRONMENT: dev-gcp:teamdatajegerne:behandlingskatalog-backend

      - name: deploy alerts to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/backend/nais/alerts.yaml

  deploy-prod-GCP:
    name: Backend - deploy Prod GCP
    needs: build
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: apps/backend/nais/behandlingskatalog-configmap-prod-gcp.yaml,apps/backend/nais/backend-gcp.yaml
          VARS: apps/backend/nais/backend-prod-gcp-vars.yaml
          ENVIRONMENT: prod-gcp:teamdatajegerne:behandlingskatalog-backend

      - name: deploy alerts to prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: apps/backend/nais/alerts.yaml


