name: Backend

on: 
  push:
    paths:
      - '.github/workflows/backend.yml'
      - 'apps/backend/**'

defaults:
  run:
    working-directory: apps/backend

jobs:
  build:
    name: Backend - build and push docker
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
      contents: read
      actions: read 
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      telemetry: ${{ steps.docker-build-push.outputs.telemetry }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17.x'

      - name: Build
        run: mvn compile

      - name: Test and Package
        run: mvn package

      - name: Build and push
        if: github.ref == 'refs/heads/prod' || github.ref == 'refs/heads/master'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamdatajegerne
          push_image: true
          image_suffix: backend
          docker_context: ./apps/backend

  deploy-dev-GCP:
    name: Backend - deploy Dev GCP
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read 
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/backend/nais/behandlingskatalog-configmap-dev-gcp.yaml,apps/backend/nais/backend-gcp.yaml
          VARS: apps/backend/nais/backend-dev-gcp-vars.yaml
          ENVIRONMENT: dev-gcp:teamdatajegerne:behandlingskatalog-backend
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}

      - name: deploy alerts to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/backend/nais/alerts.yaml

  deploy-prod-GCP:
    name: Backend - deploy Prod GCP
    needs: build
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read 
    steps:
      - uses: actions/checkout@v4

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: apps/backend/nais/behandlingskatalog-configmap-prod-gcp.yaml,apps/backend/nais/backend-gcp.yaml
          VARS: apps/backend/nais/backend-prod-gcp-vars.yaml
          ENVIRONMENT: prod-gcp:teamdatajegerne:behandlingskatalog-backend
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          TELEMETRY: ${{ needs.build.outputs.telemetry }}

      - name: deploy alerts to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: apps/backend/nais/alerts.yaml


