name: Backend

on: 
  push:
    paths:
      - '.github/workflows/backend.yml'
      - 'apps/backend/**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/polly:${{ github.sha }}

defaults:
  run:
    working-directory: apps/backend

jobs:
  build:
    name: Backend - build and push docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1.1.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15.x'
      - name: Build
        run: mvn compile
      - name: Test and Package
        run: mvn package

      - name: docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-preprod:
    name: Backend - deploy Dev FSS
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: apps/backend/nais/backend-fss.yaml
          VARS: apps/backend/nais/backend-dev-fss-vars.yaml
          ENVIRONMENT: dev-fss:teamdatajegerne:polly-backend

  deploy-dev-gcp:
    name: Backend - deploy Dev GCP
    needs: build
    if: github.ref == 'refs/heads/gcp'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/backend/nais/backend-gcp.yaml
          VARS: apps/backend/nais/backend-dev-gcp-vars.yaml
          ENVIRONMENT: dev-gcp:teamdatajegerne:polly-backend

  deploy-prod:
    name: Backend - deploy Prod FSS
    needs: build
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: apps/backend/nais/backend-fss.yaml
          VARS: apps/backend/nais/backend-prod-fss-vars.yaml
          ENVIRONMENT: prod-fss:teamdatajegerne:polly-backend
