name: Backend

on: 
  push:
    paths:
      - '.github/workflows/backend.yml'
      - 'apps/backend/**'

env:
  IMAGE: ghcr.io/${{ github.repository }}/polly:${{ github.sha }}

defaults:
  run:
    working-directory: apps/backend

jobs:
  build:
    name: Backend - build and push docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17.x'

      - name: Build
        run: mvn compile

      - name: Test and Package
        run: mvn package

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{env.IMAGE}}
          context: .

  deploy-preprod:
    name: Backend - deploy Dev FSS
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: apps/backend/nais/backend-fss.yaml
          VARS: apps/backend/nais/backend-dev-fss-vars.yaml
          ENVIRONMENT: dev-fss:teamdatajegerne:polly-backend

  deploy-prod:
    name: Backend - deploy Prod FSS
    needs: build
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: apps/backend/nais/backend-fss.yaml
          VARS: apps/backend/nais/backend-prod-fss-vars.yaml
          ENVIRONMENT: prod-fss:teamdatajegerne:polly-backend
